/**
 * Generated by scripts/generate-europe-countries.mjs.
 * The explicit 51-entry scope includes Kosovo and transcontinental states.
 */
export const europeCountries = [
  {
    code: "AL",
    names: {
      en: "Albania",
      de: "Albanien",
      es: "Albania",
      fr: "Albanie",
    },
    nativeNames: ["Shqipëria"],
  },
  {
    code: "AD",
    names: {
      en: "Andorra",
      de: "Andorra",
      es: "Andorra",
      fr: "Andorre",
    },
    nativeNames: ["Andorra"],
  },
  {
    code: "AM",
    names: {
      en: "Armenia",
      de: "Armenien",
      es: "Armenia",
      fr: "Arménie",
    },
    nativeNames: ["Հայաստան", "Hayastan"],
  },
  {
    code: "AT",
    names: {
      en: "Austria",
      de: "Österreich",
      es: "Austria",
      fr: "Autriche",
    },
    nativeNames: ["Österreich"],
  },
  {
    code: "AZ",
    names: {
      en: "Azerbaijan",
      de: "Aserbaidschan",
      es: "Azerbaiyán",
      fr: "Azerbaïdjan",
    },
    nativeNames: ["Azərbaycan"],
  },
  {
    code: "BY",
    names: {
      en: "Belarus",
      de: "Belarus",
      es: "Bielorrusia",
      fr: "Biélorussie",
    },
    nativeNames: ["Беларусь"],
  },
  {
    code: "BE",
    names: {
      en: "Belgium",
      de: "Belgien",
      es: "Bélgica",
      fr: "Belgique",
    },
    nativeNames: ["België", "Belgique", "Belgien"],
  },
  {
    code: "BA",
    names: {
      en: "Bosnia & Herzegovina",
      de: "Bosnien und Herzegowina",
      es: "Bosnia y Herzegovina",
      fr: "Bosnie-Herzégovine",
    },
    nativeNames: ["Bosna i Hercegovina", "Босна и Херцеговина"],
  },
  {
    code: "BG",
    names: {
      en: "Bulgaria",
      de: "Bulgarien",
      es: "Bulgaria",
      fr: "Bulgarie",
    },
    nativeNames: ["България"],
  },
  {
    code: "HR",
    names: {
      en: "Croatia",
      de: "Kroatien",
      es: "Croacia",
      fr: "Croatie",
    },
    nativeNames: ["Hrvatska"],
  },
  {
    code: "CY",
    names: {
      en: "Cyprus",
      de: "Zypern",
      es: "Chipre",
      fr: "Chypre",
    },
    nativeNames: ["Κύπρος", "Kıbrıs"],
  },
  {
    code: "CZ",
    names: {
      en: "Czechia",
      de: "Tschechien",
      es: "Chequia",
      fr: "Tchéquie",
    },
    nativeNames: ["Česko"],
  },
  {
    code: "DK",
    names: {
      en: "Denmark",
      de: "Dänemark",
      es: "Dinamarca",
      fr: "Danemark",
    },
    nativeNames: ["Danmark"],
  },
  {
    code: "EE",
    names: {
      en: "Estonia",
      de: "Estland",
      es: "Estonia",
      fr: "Estonie",
    },
    nativeNames: ["Eesti"],
  },
  {
    code: "FI",
    names: {
      en: "Finland",
      de: "Finnland",
      es: "Finlandia",
      fr: "Finlande",
    },
    nativeNames: ["Suomi", "Finland"],
  },
  {
    code: "FR",
    names: {
      en: "France",
      de: "Frankreich",
      es: "Francia",
      fr: "France",
    },
    nativeNames: ["France"],
  },
  {
    code: "GE",
    names: {
      en: "Georgia",
      de: "Georgien",
      es: "Georgia",
      fr: "Géorgie",
    },
    nativeNames: ["საქართველო", "Sakartvelo"],
  },
  {
    code: "DE",
    names: {
      en: "Germany",
      de: "Deutschland",
      es: "Alemania",
      fr: "Allemagne",
    },
    nativeNames: ["Deutschland"],
  },
  {
    code: "GR",
    names: {
      en: "Greece",
      de: "Griechenland",
      es: "Grecia",
      fr: "Grèce",
    },
    nativeNames: ["Ελλάδα"],
  },
  {
    code: "HU",
    names: {
      en: "Hungary",
      de: "Ungarn",
      es: "Hungría",
      fr: "Hongrie",
    },
    nativeNames: ["Magyarország"],
  },
  {
    code: "IS",
    names: {
      en: "Iceland",
      de: "Island",
      es: "Islandia",
      fr: "Islande",
    },
    nativeNames: ["Ísland"],
  },
  {
    code: "IE",
    names: {
      en: "Ireland",
      de: "Irland",
      es: "Irlanda",
      fr: "Irlande",
    },
    nativeNames: ["Éire", "Ireland"],
  },
  {
    code: "IT",
    names: {
      en: "Italy",
      de: "Italien",
      es: "Italia",
      fr: "Italie",
    },
    nativeNames: ["Italia"],
  },
  {
    code: "KZ",
    names: {
      en: "Kazakhstan",
      de: "Kasachstan",
      es: "Kazajistán",
      fr: "Kazakhstan",
    },
    nativeNames: ["Қазақстан", "Казахстан"],
  },
  {
    code: "XK",
    names: {
      en: "Kosovo",
      de: "Kosovo",
      es: "Kosovo",
      fr: "Kosovo",
    },
    nativeNames: ["Kosova", "Косово"],
  },
  {
    code: "LV",
    names: {
      en: "Latvia",
      de: "Lettland",
      es: "Letonia",
      fr: "Lettonie",
    },
    nativeNames: ["Latvija"],
  },
  {
    code: "LI",
    names: {
      en: "Liechtenstein",
      de: "Liechtenstein",
      es: "Liechtenstein",
      fr: "Liechtenstein",
    },
    nativeNames: ["Liechtenstein"],
  },
  {
    code: "LT",
    names: {
      en: "Lithuania",
      de: "Litauen",
      es: "Lituania",
      fr: "Lituanie",
    },
    nativeNames: ["Lietuva"],
  },
  {
    code: "LU",
    names: {
      en: "Luxembourg",
      de: "Luxemburg",
      es: "Luxemburgo",
      fr: "Luxembourg",
    },
    nativeNames: ["Lëtzebuerg", "Luxembourg", "Luxemburg"],
  },
  {
    code: "MT",
    names: {
      en: "Malta",
      de: "Malta",
      es: "Malta",
      fr: "Malte",
    },
    nativeNames: ["Malta"],
  },
  {
    code: "MD",
    names: {
      en: "Moldova",
      de: "Republik Moldau",
      es: "Moldavia",
      fr: "Moldavie",
    },
    nativeNames: ["Moldova"],
  },
  {
    code: "MC",
    names: {
      en: "Monaco",
      de: "Monaco",
      es: "Mónaco",
      fr: "Monaco",
    },
    nativeNames: ["Monaco"],
  },
  {
    code: "ME",
    names: {
      en: "Montenegro",
      de: "Montenegro",
      es: "Montenegro",
      fr: "Monténégro",
    },
    nativeNames: ["Crna Gora", "Црна Гора"],
  },
  {
    code: "NL",
    names: {
      en: "Netherlands",
      de: "Niederlande",
      es: "Países Bajos",
      fr: "Pays-Bas",
    },
    nativeNames: ["Nederland"],
  },
  {
    code: "MK",
    names: {
      en: "North Macedonia",
      de: "Nordmazedonien",
      es: "Macedonia del Norte",
      fr: "Macédoine du Nord",
    },
    nativeNames: ["Северна Македонија", "Maqedonia e Veriut"],
  },
  {
    code: "NO",
    names: {
      en: "Norway",
      de: "Norwegen",
      es: "Noruega",
      fr: "Norvège",
    },
    nativeNames: ["Norge", "Noreg"],
  },
  {
    code: "PL",
    names: {
      en: "Poland",
      de: "Polen",
      es: "Polonia",
      fr: "Pologne",
    },
    nativeNames: ["Polska"],
  },
  {
    code: "PT",
    names: {
      en: "Portugal",
      de: "Portugal",
      es: "Portugal",
      fr: "Portugal",
    },
    nativeNames: ["Portugal"],
  },
  {
    code: "RO",
    names: {
      en: "Romania",
      de: "Rumänien",
      es: "Rumanía",
      fr: "Roumanie",
    },
    nativeNames: ["România"],
  },
  {
    code: "RU",
    names: {
      en: "Russia",
      de: "Russland",
      es: "Rusia",
      fr: "Russie",
    },
    nativeNames: ["Россия"],
  },
  {
    code: "SM",
    names: {
      en: "San Marino",
      de: "San Marino",
      es: "San Marino",
      fr: "Saint-Marin",
    },
    nativeNames: ["San Marino"],
  },
  {
    code: "RS",
    names: {
      en: "Serbia",
      de: "Serbien",
      es: "Serbia",
      fr: "Serbie",
    },
    nativeNames: ["Србија", "Srbija"],
  },
  {
    code: "SK",
    names: {
      en: "Slovakia",
      de: "Slowakei",
      es: "Eslovaquia",
      fr: "Slovaquie",
    },
    nativeNames: ["Slovensko"],
  },
  {
    code: "SI",
    names: {
      en: "Slovenia",
      de: "Slowenien",
      es: "Eslovenia",
      fr: "Slovénie",
    },
    nativeNames: ["Slovenija"],
  },
  {
    code: "ES",
    names: {
      en: "Spain",
      de: "Spanien",
      es: "España",
      fr: "Espagne",
    },
    nativeNames: ["España"],
  },
  {
    code: "SE",
    names: {
      en: "Sweden",
      de: "Schweden",
      es: "Suecia",
      fr: "Suède",
    },
    nativeNames: ["Sverige"],
  },
  {
    code: "CH",
    names: {
      en: "Switzerland",
      de: "Schweiz",
      es: "Suiza",
      fr: "Suisse",
    },
    nativeNames: ["Schweiz", "Suisse", "Svizzera", "Svizra"],
  },
  {
    code: "TR",
    names: {
      en: "Türkiye",
      de: "Türkei",
      es: "Turquía",
      fr: "Turquie",
    },
    nativeNames: ["Türkiye"],
  },
  {
    code: "UA",
    names: {
      en: "Ukraine",
      de: "Ukraine",
      es: "Ucrania",
      fr: "Ukraine",
    },
    nativeNames: ["Україна"],
  },
  {
    code: "GB",
    names: {
      en: "United Kingdom",
      de: "Vereinigtes Königreich",
      es: "Reino Unido",
      fr: "Royaume-Uni",
    },
    nativeNames: ["United Kingdom", "Y Deyrnas Unedig"],
  },
  {
    code: "VA",
    names: {
      en: "Vatican City",
      de: "Vatikanstadt",
      es: "Ciudad del Vaticano",
      fr: "État de la Cité du Vatican",
    },
    nativeNames: ["Città del Vaticano", "Status Civitatis Vaticanae"],
  },
] as const;

export type EuropeCountryCode = (typeof europeCountries)[number]["code"];
export type EuropeContentLocale = "en" | "de" | "es" | "fr";

export const europeContentLocales = ["en", "de", "es", "fr"] as const;

export const getEuropeCountry = (code: string) =>
  europeCountries.find((country) => country.code === code);

export const getEuropeCountryName = (
  code: string,
  locale: EuropeContentLocale,
): string => getEuropeCountry(code)?.names[locale] ?? code;
