// Generated from the PubChem Periodic Table PUG REST dataset.
// Source: https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON
// Retrieved: 2026-08-27

export type PeriodicTableElement = {
  atomicNumber: number;
  symbol: string;
  name: string;
  atomicMass: string;
  electronConfiguration: string;
  electronegativity: string | null;
  standardState: string;
  category: string;
  yearDiscovered: string;
};

export const periodicTableElements: readonly PeriodicTableElement[] = [
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: "1.0080",
    electronConfiguration: "1s1",
    electronegativity: "2.2",
    standardState: "Gas",
    category: "Nonmetal",
    yearDiscovered: "1766",
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: "4.00260",
    electronConfiguration: "1s2",
    electronegativity: null,
    standardState: "Gas",
    category: "Noble gas",
    yearDiscovered: "1868",
  },
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: "7.0",
    electronConfiguration: "[He]2s1",
    electronegativity: "0.98",
    standardState: "Solid",
    category: "Alkali metal",
    yearDiscovered: "1817",
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: "9.012183",
    electronConfiguration: "[He]2s2",
    electronegativity: "1.57",
    standardState: "Solid",
    category: "Alkaline earth metal",
    yearDiscovered: "1798",
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: "10.81",
    electronConfiguration: "[He]2s2 2p1",
    electronegativity: "2.04",
    standardState: "Solid",
    category: "Metalloid",
    yearDiscovered: "1808",
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: "12.011",
    electronConfiguration: "[He]2s2 2p2",
    electronegativity: "2.55",
    standardState: "Solid",
    category: "Nonmetal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: "14.007",
    electronConfiguration: "[He] 2s2 2p3",
    electronegativity: "3.04",
    standardState: "Gas",
    category: "Nonmetal",
    yearDiscovered: "1772",
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: "15.999",
    electronConfiguration: "[He]2s2 2p4",
    electronegativity: "3.44",
    standardState: "Gas",
    category: "Nonmetal",
    yearDiscovered: "1774",
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: "18.99840316",
    electronConfiguration: "[He]2s2 2p5",
    electronegativity: "3.98",
    standardState: "Gas",
    category: "Halogen",
    yearDiscovered: "1670",
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: "20.180",
    electronConfiguration: "[He]2s2 2p6",
    electronegativity: null,
    standardState: "Gas",
    category: "Noble gas",
    yearDiscovered: "1898",
  },
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: "22.9897693",
    electronConfiguration: "[Ne]3s1",
    electronegativity: "0.93",
    standardState: "Solid",
    category: "Alkali metal",
    yearDiscovered: "1807",
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: "24.305",
    electronConfiguration: "[Ne]3s2",
    electronegativity: "1.31",
    standardState: "Solid",
    category: "Alkaline earth metal",
    yearDiscovered: "1808",
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicMass: "26.981538",
    electronConfiguration: "[Ne]3s2 3p1",
    electronegativity: "1.61",
    standardState: "Solid",
    category: "Post-transition metal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: "28.085",
    electronConfiguration: "[Ne]3s2 3p2",
    electronegativity: "1.9",
    standardState: "Solid",
    category: "Metalloid",
    yearDiscovered: "1854",
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: "30.97376200",
    electronConfiguration: "[Ne]3s2 3p3",
    electronegativity: "2.19",
    standardState: "Solid",
    category: "Nonmetal",
    yearDiscovered: "1669",
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: "32.07",
    electronConfiguration: "[Ne]3s2 3p4",
    electronegativity: "2.58",
    standardState: "Solid",
    category: "Nonmetal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: "35.45",
    electronConfiguration: "[Ne]3s2 3p5",
    electronegativity: "3.16",
    standardState: "Gas",
    category: "Halogen",
    yearDiscovered: "1774",
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: "39.9",
    electronConfiguration: "[Ne]3s2 3p6",
    electronegativity: null,
    standardState: "Gas",
    category: "Noble gas",
    yearDiscovered: "1894",
  },
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: "39.0983",
    electronConfiguration: "[Ar]4s1",
    electronegativity: "0.82",
    standardState: "Solid",
    category: "Alkali metal",
    yearDiscovered: "1807",
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: "40.08",
    electronConfiguration: "[Ar]4s2",
    electronegativity: "1",
    standardState: "Solid",
    category: "Alkaline earth metal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: "44.95591",
    electronConfiguration: "[Ar]4s2 3d1",
    electronegativity: "1.36",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1879",
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: "47.867",
    electronConfiguration: "[Ar]4s2 3d2",
    electronegativity: "1.54",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1791",
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: "50.9415",
    electronConfiguration: "[Ar]4s2 3d3",
    electronegativity: "1.63",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1801",
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: "51.996",
    electronConfiguration: "[Ar]3d5 4s1",
    electronegativity: "1.66",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1797",
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: "54.93804",
    electronConfiguration: "[Ar]4s2 3d5",
    electronegativity: "1.55",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1774",
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: "55.84",
    electronConfiguration: "[Ar]4s2 3d6",
    electronegativity: "1.83",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: "58.93319",
    electronConfiguration: "[Ar]4s2 3d7",
    electronegativity: "1.88",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1735",
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: "58.693",
    electronConfiguration: "[Ar]4s2 3d8",
    electronegativity: "1.91",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1751",
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: "63.55",
    electronConfiguration: "[Ar]4s1 3d10",
    electronegativity: "1.9",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: "65.4",
    electronConfiguration: "[Ar]4s2 3d10",
    electronegativity: "1.65",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1746",
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: "69.723",
    electronConfiguration: "[Ar]4s2 3d10 4p1",
    electronegativity: "1.81",
    standardState: "Solid",
    category: "Post-transition metal",
    yearDiscovered: "1875",
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: "72.63",
    electronConfiguration: "[Ar]4s2 3d10 4p2",
    electronegativity: "2.01",
    standardState: "Solid",
    category: "Metalloid",
    yearDiscovered: "1886",
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: "74.92159",
    electronConfiguration: "[Ar]4s2 3d10 4p3",
    electronegativity: "2.18",
    standardState: "Solid",
    category: "Metalloid",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: "78.97",
    electronConfiguration: "[Ar]4s2 3d10 4p4",
    electronegativity: "2.55",
    standardState: "Solid",
    category: "Nonmetal",
    yearDiscovered: "1817",
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: "79.90",
    electronConfiguration: "[Ar]4s2 3d10 4p5",
    electronegativity: "2.96",
    standardState: "Liquid",
    category: "Halogen",
    yearDiscovered: "1826",
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: "83.80",
    electronConfiguration: "[Ar]4s2 3d10 4p6",
    electronegativity: "3",
    standardState: "Gas",
    category: "Noble gas",
    yearDiscovered: "1898",
  },
  {
    atomicNumber: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicMass: "85.468",
    electronConfiguration: "[Kr]5s1",
    electronegativity: "0.82",
    standardState: "Solid",
    category: "Alkali metal",
    yearDiscovered: "1861",
  },
  {
    atomicNumber: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicMass: "87.62",
    electronConfiguration: "[Kr]5s2",
    electronegativity: "0.95",
    standardState: "Solid",
    category: "Alkaline earth metal",
    yearDiscovered: "1790",
  },
  {
    atomicNumber: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicMass: "88.90584",
    electronConfiguration: "[Kr]5s2 4d1",
    electronegativity: "1.22",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1794",
  },
  {
    atomicNumber: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicMass: "91.22",
    electronConfiguration: "[Kr]5s2 4d2",
    electronegativity: "1.33",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1789",
  },
  {
    atomicNumber: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicMass: "92.90637",
    electronConfiguration: "[Kr]5s1 4d4",
    electronegativity: "1.6",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1801",
  },
  {
    atomicNumber: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicMass: "95.95",
    electronConfiguration: "[Kr]5s1 4d5",
    electronegativity: "2.16",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1778",
  },
  {
    atomicNumber: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicMass: "96.90636",
    electronConfiguration: "[Kr]5s2 4d5",
    electronegativity: "1.9",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1937",
  },
  {
    atomicNumber: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicMass: "101.1",
    electronConfiguration: "[Kr]5s1 4d7",
    electronegativity: "2.2",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1827",
  },
  {
    atomicNumber: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicMass: "102.9055",
    electronConfiguration: "[Kr]5s1 4d8",
    electronegativity: "2.28",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1803",
  },
  {
    atomicNumber: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicMass: "106.42",
    electronConfiguration: "[Kr]4d10",
    electronegativity: "2.2",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1803",
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    atomicMass: "107.868",
    electronConfiguration: "[Kr]5s1 4d10",
    electronegativity: "1.93",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicMass: "112.41",
    electronConfiguration: "[Kr]5s2 4d10",
    electronegativity: "1.69",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1817",
  },
  {
    atomicNumber: 49,
    symbol: "In",
    name: "Indium",
    atomicMass: "114.818",
    electronConfiguration: "[Kr]5s2 4d10 5p1",
    electronegativity: "1.78",
    standardState: "Solid",
    category: "Post-transition metal",
    yearDiscovered: "1863",
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    atomicMass: "118.71",
    electronConfiguration: "[Kr]5s2 4d10 5p2",
    electronegativity: "1.96",
    standardState: "Solid",
    category: "Post-transition metal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicMass: "121.760",
    electronConfiguration: "[Kr]5s2 4d10 5p3",
    electronegativity: "2.05",
    standardState: "Solid",
    category: "Metalloid",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicMass: "127.6",
    electronConfiguration: "[Kr]5s2 4d10 5p4",
    electronegativity: "2.1",
    standardState: "Solid",
    category: "Metalloid",
    yearDiscovered: "1782",
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    atomicMass: "126.9045",
    electronConfiguration: "[Kr]5s2 4d10 5p5",
    electronegativity: "2.66",
    standardState: "Solid",
    category: "Halogen",
    yearDiscovered: "1811",
  },
  {
    atomicNumber: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicMass: "131.29",
    electronConfiguration: "[Kr]5s2 4d10 5p6",
    electronegativity: "2.6",
    standardState: "Gas",
    category: "Noble gas",
    yearDiscovered: "1898",
  },
  {
    atomicNumber: 55,
    symbol: "Cs",
    name: "Cesium",
    atomicMass: "132.9054520",
    electronConfiguration: "[Xe]6s1",
    electronegativity: "0.79",
    standardState: "Solid",
    category: "Alkali metal",
    yearDiscovered: "1860",
  },
  {
    atomicNumber: 56,
    symbol: "Ba",
    name: "Barium",
    atomicMass: "137.33",
    electronConfiguration: "[Xe]6s2",
    electronegativity: "0.89",
    standardState: "Solid",
    category: "Alkaline earth metal",
    yearDiscovered: "1808",
  },
  {
    atomicNumber: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicMass: "138.9055",
    electronConfiguration: "[Xe]6s2 5d1",
    electronegativity: "1.1",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1839",
  },
  {
    atomicNumber: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicMass: "140.116",
    electronConfiguration: "[Xe]6s2 4f1 5d1",
    electronegativity: "1.12",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1803",
  },
  {
    atomicNumber: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicMass: "140.90766",
    electronConfiguration: "[Xe]6s2 4f3",
    electronegativity: "1.13",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1885",
  },
  {
    atomicNumber: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicMass: "144.24",
    electronConfiguration: "[Xe]6s2 4f4",
    electronegativity: "1.14",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1885",
  },
  {
    atomicNumber: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicMass: "144.91276",
    electronConfiguration: "[Xe]6s2 4f5",
    electronegativity: null,
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1945",
  },
  {
    atomicNumber: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicMass: "150.4",
    electronConfiguration: "[Xe]6s2 4f6",
    electronegativity: "1.17",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1879",
  },
  {
    atomicNumber: 63,
    symbol: "Eu",
    name: "Europium",
    atomicMass: "151.964",
    electronConfiguration: "[Xe]6s2 4f7",
    electronegativity: null,
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1901",
  },
  {
    atomicNumber: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicMass: "157.25",
    electronConfiguration: "[Xe]6s2 4f7 5d1",
    electronegativity: "1.2",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1880",
  },
  {
    atomicNumber: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicMass: "158.92535",
    electronConfiguration: "[Xe]6s2 4f9",
    electronegativity: null,
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1843",
  },
  {
    atomicNumber: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicMass: "162.500",
    electronConfiguration: "[Xe]6s2 4f10",
    electronegativity: "1.22",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1886",
  },
  {
    atomicNumber: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicMass: "164.93033",
    electronConfiguration: "[Xe]6s2 4f11",
    electronegativity: "1.23",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1878",
  },
  {
    atomicNumber: 68,
    symbol: "Er",
    name: "Erbium",
    atomicMass: "167.26",
    electronConfiguration: "[Xe]6s2 4f12",
    electronegativity: "1.24",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1843",
  },
  {
    atomicNumber: 69,
    symbol: "Tm",
    name: "Thulium",
    atomicMass: "168.93422",
    electronConfiguration: "[Xe]6s2 4f13",
    electronegativity: "1.25",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1879",
  },
  {
    atomicNumber: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomicMass: "173.05",
    electronConfiguration: "[Xe]6s2 4f14",
    electronegativity: null,
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1878",
  },
  {
    atomicNumber: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomicMass: "174.9667",
    electronConfiguration: "[Xe]6s2 4f14 5d1",
    electronegativity: "1.27",
    standardState: "Solid",
    category: "Lanthanide",
    yearDiscovered: "1907",
  },
  {
    atomicNumber: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomicMass: "178.49",
    electronConfiguration: "[Xe]6s2 4f14 5d2",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1923",
  },
  {
    atomicNumber: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomicMass: "180.9479",
    electronConfiguration: "[Xe]6s2 4f14 5d3",
    electronegativity: "1.5",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1802",
  },
  {
    atomicNumber: 74,
    symbol: "W",
    name: "Tungsten",
    atomicMass: "183.84",
    electronConfiguration: "[Xe]6s2 4f14 5d4",
    electronegativity: "2.36",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1783",
  },
  {
    atomicNumber: 75,
    symbol: "Re",
    name: "Rhenium",
    atomicMass: "186.207",
    electronConfiguration: "[Xe]6s2 4f14 5d5",
    electronegativity: "1.9",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1925",
  },
  {
    atomicNumber: 76,
    symbol: "Os",
    name: "Osmium",
    atomicMass: "190.2",
    electronConfiguration: "[Xe]6s2 4f14 5d6",
    electronegativity: "2.2",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1803",
  },
  {
    atomicNumber: 77,
    symbol: "Ir",
    name: "Iridium",
    atomicMass: "192.22",
    electronConfiguration: "[Xe]6s2 4f14 5d7",
    electronegativity: "2.2",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1803",
  },
  {
    atomicNumber: 78,
    symbol: "Pt",
    name: "Platinum",
    atomicMass: "195.08",
    electronConfiguration: "[Xe]6s1 4f14 5d9",
    electronegativity: "2.28",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1735",
  },
  {
    atomicNumber: 79,
    symbol: "Au",
    name: "Gold",
    atomicMass: "196.96657",
    electronConfiguration: "[Xe]6s1 4f14 5d10",
    electronegativity: "2.54",
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicMass: "200.59",
    electronConfiguration: "[Xe]6s2 4f14 5d10",
    electronegativity: "2",
    standardState: "Liquid",
    category: "Transition metal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicMass: "204.383",
    electronConfiguration: "[Xe]6s2 4f14 5d10 6p1",
    electronegativity: "1.62",
    standardState: "Solid",
    category: "Post-transition metal",
    yearDiscovered: "1861",
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: "207",
    electronConfiguration: "[Xe]6s2 4f14 5d10 6p2",
    electronegativity: "2.33",
    standardState: "Solid",
    category: "Post-transition metal",
    yearDiscovered: "Ancient",
  },
  {
    atomicNumber: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicMass: "208.98040",
    electronConfiguration: "[Xe]6s2 4f14 5d10 6p3",
    electronegativity: "2.02",
    standardState: "Solid",
    category: "Post-transition metal",
    yearDiscovered: "1753",
  },
  {
    atomicNumber: 84,
    symbol: "Po",
    name: "Polonium",
    atomicMass: "208.98243",
    electronConfiguration: "[Xe]6s2 4f14 5d10 6p4",
    electronegativity: "2",
    standardState: "Solid",
    category: "Metalloid",
    yearDiscovered: "1898",
  },
  {
    atomicNumber: 85,
    symbol: "At",
    name: "Astatine",
    atomicMass: "209.98715",
    electronConfiguration: "[Xe]6s2 4f14 5d10 6p5",
    electronegativity: "2.2",
    standardState: "Solid",
    category: "Halogen",
    yearDiscovered: "1940",
  },
  {
    atomicNumber: 86,
    symbol: "Rn",
    name: "Radon",
    atomicMass: "222.01758",
    electronConfiguration: "[Xe]6s2 4f14 5d10 6p6",
    electronegativity: null,
    standardState: "Gas",
    category: "Noble gas",
    yearDiscovered: "1900",
  },
  {
    atomicNumber: 87,
    symbol: "Fr",
    name: "Francium",
    atomicMass: "223.01973",
    electronConfiguration: "[Rn]7s1",
    electronegativity: "0.7",
    standardState: "Solid",
    category: "Alkali metal",
    yearDiscovered: "1939",
  },
  {
    atomicNumber: 88,
    symbol: "Ra",
    name: "Radium",
    atomicMass: "226.02541",
    electronConfiguration: "[Rn]7s2",
    electronegativity: "0.9",
    standardState: "Solid",
    category: "Alkaline earth metal",
    yearDiscovered: "1898",
  },
  {
    atomicNumber: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicMass: "227.02775",
    electronConfiguration: "[Rn]7s2 6d1",
    electronegativity: "1.1",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1899",
  },
  {
    atomicNumber: 90,
    symbol: "Th",
    name: "Thorium",
    atomicMass: "232.038",
    electronConfiguration: "[Rn]7s2 6d2",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1828",
  },
  {
    atomicNumber: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicMass: "231.03588",
    electronConfiguration: "[Rn]7s2 5f2 6d1",
    electronegativity: "1.5",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1913",
  },
  {
    atomicNumber: 92,
    symbol: "U",
    name: "Uranium",
    atomicMass: "238.0289",
    electronConfiguration: "[Rn]7s2 5f3 6d1",
    electronegativity: "1.38",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1789",
  },
  {
    atomicNumber: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicMass: "237.048172",
    electronConfiguration: "[Rn]7s2 5f4 6d1",
    electronegativity: "1.36",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1940",
  },
  {
    atomicNumber: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomicMass: "244.06420",
    electronConfiguration: "[Rn]7s2 5f6",
    electronegativity: "1.28",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1940",
  },
  {
    atomicNumber: 95,
    symbol: "Am",
    name: "Americium",
    atomicMass: "243.061380",
    electronConfiguration: "[Rn]7s2 5f7",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1944",
  },
  {
    atomicNumber: 96,
    symbol: "Cm",
    name: "Curium",
    atomicMass: "247.07035",
    electronConfiguration: "[Rn]7s2 5f7 6d1",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1944",
  },
  {
    atomicNumber: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomicMass: "247.07031",
    electronConfiguration: "[Rn]7s2 5f9",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1949",
  },
  {
    atomicNumber: 98,
    symbol: "Cf",
    name: "Californium",
    atomicMass: "251.07959",
    electronConfiguration: "[Rn]7s2 5f10",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1950",
  },
  {
    atomicNumber: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomicMass: "252.0830",
    electronConfiguration: "[Rn]7s2 5f11",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1952",
  },
  {
    atomicNumber: 100,
    symbol: "Fm",
    name: "Fermium",
    atomicMass: "257.09511",
    electronConfiguration: "[Rn] 5f12 7s2",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1952",
  },
  {
    atomicNumber: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomicMass: "258.09843",
    electronConfiguration: "[Rn]7s2 5f13",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1955",
  },
  {
    atomicNumber: 102,
    symbol: "No",
    name: "Nobelium",
    atomicMass: "259.10100",
    electronConfiguration: "[Rn]7s2 5f14",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1957",
  },
  {
    atomicNumber: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomicMass: "266.120",
    electronConfiguration: "[Rn]7s2 5f14 6d1",
    electronegativity: "1.3",
    standardState: "Solid",
    category: "Actinide",
    yearDiscovered: "1961",
  },
  {
    atomicNumber: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicMass: "267.122",
    electronConfiguration: "[Rn]7s2 5f14 6d2",
    electronegativity: null,
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1964",
  },
  {
    atomicNumber: 105,
    symbol: "Db",
    name: "Dubnium",
    atomicMass: "268.126",
    electronConfiguration: "[Rn]7s2 5f14 6d3",
    electronegativity: null,
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1967",
  },
  {
    atomicNumber: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomicMass: "269.128",
    electronConfiguration: "[Rn]7s2 5f14 6d4",
    electronegativity: null,
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1974",
  },
  {
    atomicNumber: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomicMass: "270.133",
    electronConfiguration: "[Rn]7s2 5f14 6d5",
    electronegativity: null,
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1976",
  },
  {
    atomicNumber: 108,
    symbol: "Hs",
    name: "Hassium",
    atomicMass: "269.1336",
    electronConfiguration: "[Rn]7s2 5f14 6d6",
    electronegativity: null,
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1984",
  },
  {
    atomicNumber: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicMass: "277.154",
    electronConfiguration: "[Rn]7s2 5f14 6d7 (calculated)",
    electronegativity: null,
    standardState: "Solid",
    category: "Transition metal",
    yearDiscovered: "1982",
  },
  {
    atomicNumber: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomicMass: "282.166",
    electronConfiguration: "[Rn]7s2 5f14 6d8 (predicted)",
    electronegativity: null,
    standardState: "Expected to be a Solid",
    category: "Transition metal",
    yearDiscovered: "1994",
  },
  {
    atomicNumber: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomicMass: "282.169",
    electronConfiguration: "[Rn]7s2 5f14 6d9 (predicted)",
    electronegativity: null,
    standardState: "Expected to be a Solid",
    category: "Transition metal",
    yearDiscovered: "1994",
  },
  {
    atomicNumber: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomicMass: "286.179",
    electronConfiguration: "[Rn]7s2 5f14 6d10 (predicted)",
    electronegativity: null,
    standardState: "Expected to be a Solid",
    category: "Transition metal",
    yearDiscovered: "1996",
  },
  {
    atomicNumber: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicMass: "286.182",
    electronConfiguration: "[Rn]5f14 6d10 7s2 7p1 (predicted)",
    electronegativity: null,
    standardState: "Expected to be a Solid",
    category: "Post-transition metal",
    yearDiscovered: "2004",
  },
  {
    atomicNumber: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicMass: "290.192",
    electronConfiguration: "[Rn]7s2 7p2 5f14 6d10 (predicted)",
    electronegativity: null,
    standardState: "Expected to be a Solid",
    category: "Post-transition metal",
    yearDiscovered: "1998",
  },
  {
    atomicNumber: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicMass: "290.196",
    electronConfiguration: "[Rn]7s2 7p3 5f14 6d10 (predicted)",
    electronegativity: null,
    standardState: "Expected to be a Solid",
    category: "Post-transition metal",
    yearDiscovered: "2003",
  },
  {
    atomicNumber: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicMass: "293.205",
    electronConfiguration: "[Rn]7s2 7p4 5f14 6d10 (predicted)",
    electronegativity: null,
    standardState: "Expected to be a Solid",
    category: "Post-transition metal",
    yearDiscovered: "2000",
  },
  {
    atomicNumber: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicMass: "294.211",
    electronConfiguration: "[Rn]7s2 7p5 5f14 6d10 (predicted)",
    electronegativity: null,
    standardState: "Expected to be a Solid",
    category: "Halogen",
    yearDiscovered: "2010",
  },
  {
    atomicNumber: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicMass: "295.216",
    electronConfiguration: "[Rn]7s2 7p6 5f14 6d10 (predicted)",
    electronegativity: null,
    standardState: "Expected to be a Gas",
    category: "Noble gas",
    yearDiscovered: "2006",
  },
];
