import type {
  DeveloperReferenceDefinition,
  ReferenceCardSpec,
  ReferenceDeckSpec,
} from "./developer-reference-model.js";

type CodeLanguage = NonNullable<ReferenceCardSpec["exampleLanguage"]>;
type CompactCard = readonly [
  key: string,
  title: string,
  command: string,
  explanation: string,
  example: string,
  note?: string,
];

const cards = (
  language: CodeLanguage,
  rows: readonly CompactCard[],
): ReferenceCardSpec[] =>
  rows.map(([key, title, command, explanation, example, note]) => ({
    key,
    title,
    command,
    explanation,
    example,
    note,
    commandLanguage: language,
    exampleLanguage: language,
  }));

const deck = (
  key: ReferenceDeckSpec["key"],
  title: string,
  description: string,
  language: CodeLanguage,
  rows: readonly CompactCard[],
): ReferenceDeckSpec => ({
  key,
  title,
  description,
  cards: cards(language, rows).map((card, index) => {
    if (key !== "samples") return card;
    const sampleTitle = card.title.replace(/^Sample:\s*/, "");
    return {
      ...card,
      title: `Sample ${index + 1}: ${sampleTitle.charAt(0).toUpperCase()}${sampleTitle.slice(1)}`,
    };
  }),
});

const definition = (
  id: DeveloperReferenceDefinition["id"],
  title: string,
  description: string,
  tags: string[],
  language: CodeLanguage,
  introduction: readonly CompactCard[],
  advanced: readonly CompactCard[],
  samples: readonly CompactCard[],
): DeveloperReferenceDefinition => ({
  id,
  templateKey: `developer:${id}-reference:v1`,
  title,
  description,
  tags: [...tags, "Developer reference"],
  decks: [
    deck(
      "introduction",
      `01 · ${title.replace(" Developer Reference", "")} Introduction`,
      "The commands and concepts used in everyday work.",
      language,
      introduction,
    ),
    deck(
      "advanced",
      `02 · Advanced ${title.replace(" Developer Reference", "")}`,
      "Deeper control, diagnostics, portability, and safe automation.",
      language,
      advanced,
    ),
    deck(
      "samples",
      `03 · Practical ${title.replace(" Developer Reference", "")} Samples`,
      "Complete patterns adapted from common development workflows.",
      language,
      samples,
    ),
  ],
});

const httpCurlDefinition = definition(
  "http-curl",
  "HTTP & cURL Developer Reference",
  "HTTP fundamentals, robust cURL diagnostics, authentication, uploads, and practical API workflows.",
  ["HTTP", "cURL", "API"],
  "bash",
  [
    [
      "get",
      "Send a GET request",
      "curl https://api.example.test/items",
      "Requests a representation with HTTP GET and writes the response body to standard output.",
      "curl --fail-with-body --silent --show-error https://api.example.test/health",
    ],
    [
      "headers",
      "Add request headers",
      'curl -H "Accept: application/json" URL',
      "Adds metadata such as accepted response formats, correlation IDs, or API versions.",
      'curl -H "Accept: application/json" -H "X-Request-ID: demo-42" https://api.example.test/items',
    ],
    [
      "status",
      "Inspect status and response headers",
      "curl -i URL",
      "Includes the status line and response headers so redirects, caching, and content negotiation are visible.",
      "curl --silent --show-error --dump-header - --output /dev/null https://api.example.test/items",
    ],
    [
      "json-post",
      "Send JSON",
      'curl --json \'{"name":"Ada"}\' URL',
      "Sets the JSON content type and sends a POST request with the supplied document.",
      'curl --fail-with-body --json \'{"title":"Draft"}\' https://api.example.test/items',
    ],
    [
      "methods",
      "Choose an HTTP method",
      "curl -X PATCH URL",
      "Selects a method explicitly. Data options already imply POST, so -X is most useful for PATCH, PUT, and DELETE.",
      "curl --request PATCH --json '{\"active\":true}' https://api.example.test/items/42",
    ],
    [
      "bearer",
      "Use bearer authentication",
      'curl -H "Authorization: Bearer $API_TOKEN" URL',
      "Carries an access token in the Authorization header without placing it in the URL.",
      'curl --fail-with-body -H "Authorization: Bearer $API_TOKEN" https://api.example.test/me',
      "Keep tokens in a protected secret store and prevent shell history or debug logs from exposing them.",
    ],
    [
      "basic",
      "Use HTTP Basic authentication",
      "curl --user username URL",
      "Builds a Basic Authorization header and prompts for the password when only the user name is supplied.",
      "curl --user ci-bot https://api.example.test/private",
      "Do not put passwords directly on the command line; process listings and shell history may reveal them.",
    ],
    [
      "download",
      "Save a response",
      "curl --output artifact.zip URL",
      "Writes the body to a file instead of the terminal. --remote-name uses the final URL path as the file name.",
      "curl --fail --location --output release.zip https://downloads.example.test/release.zip",
    ],
  ],
  [
    [
      "timeouts",
      "Bound connection and request time",
      "curl --connect-timeout 5 --max-time 30 URL",
      "Prevents automation from waiting indefinitely for a connection or response.",
      "curl --fail --connect-timeout 3 --max-time 15 https://api.example.test/health",
    ],
    [
      "retry",
      "Retry transient failures",
      "curl --retry 4 --retry-all-errors URL",
      "Retries temporary transport and server failures. Only repeat requests whose semantics are safe for the application.",
      "curl --fail --retry 4 --retry-delay 2 --retry-max-time 30 https://api.example.test/status",
      "Avoid blindly retrying non-idempotent writes because the server may already have applied them.",
    ],
    [
      "redirect-cookie",
      "Follow redirects and retain cookies",
      "curl --location --cookie-jar cookies.txt --cookie cookies.txt URL",
      "Follows Location headers and persists a session cookie jar between requests.",
      "curl --location --cookie-jar session.cookies --cookie session.cookies https://app.example.test/login",
      "Cookie jars can contain live session credentials; restrict permissions and delete them when no longer needed.",
    ],
    [
      "multipart",
      "Upload multipart form data",
      'curl --form "file=@report.pdf" --form "label=Q2" URL',
      "Builds a multipart request suitable for file uploads and accompanying text fields.",
      'curl --fail-with-body --form "file=@./report.pdf;type=application/pdf" https://api.example.test/uploads',
    ],
    [
      "tls",
      "Inspect a TLS connection",
      "curl --verbose https://host.example.test",
      "Shows certificate negotiation, request headers, and response headers for transport diagnosis.",
      "curl --verbose --cacert ./company-root.pem https://internal.example.test/health",
      "Do not normalize --insecure as a fix. Install or select the correct trusted CA instead.",
    ],
    [
      "timing",
      "Measure request phases",
      "curl --write-out FORMAT --output /dev/null URL",
      "Reports DNS, connection, TLS, first-byte, and total duration without mixing metrics into the body.",
      "curl --silent --output /dev/null --write-out 'dns=%{time_namelookup} connect=%{time_connect} ttfb=%{time_starttransfer} total=%{time_total}\\n' https://api.example.test/items",
    ],
  ],
  [
    [
      "sample-health",
      "Sample: fail a health check correctly",
      "curl --fail-with-body --silent --show-error URL",
      "Makes non-success status codes fail the command while preserving the server error body.",
      "curl --fail-with-body --silent --show-error --max-time 10 https://service.example.test/health",
    ],
    [
      "sample-pagination",
      "Sample: fetch a page of API results",
      "curl --get --data-urlencode key=value URL",
      "Encodes query parameters safely instead of assembling a URL by hand.",
      "curl --fail-with-body --get --data-urlencode 'page=2' --data-urlencode 'search=release notes' https://api.example.test/items",
    ],
    [
      "sample-create",
      "Sample: create a resource",
      "curl --json @payload.json URL",
      "Reads a JSON body from a reviewed file, which is easier to version and validate than complex shell quoting.",
      "curl --fail-with-body --header 'Authorization: Bearer '$API_TOKEN --json @new-item.json https://api.example.test/items",
    ],
    [
      "sample-upload",
      "Sample: upload an artifact",
      "curl --form file=@PATH URL",
      "Uploads a local artifact and fails visibly if the server rejects it.",
      "curl --fail-with-body --form 'file=@./dist/app.tar.gz;type=application/gzip' https://api.example.test/artifacts",
    ],
    [
      "sample-cache",
      "Sample: perform a conditional request",
      'curl -H "If-None-Match: ETAG" URL',
      "Lets the server answer 304 Not Modified when the cached representation is still current.",
      "curl --silent --dump-header response.headers --header 'If-None-Match: \"v42\"' https://api.example.test/catalog",
    ],
    [
      "sample-debug",
      "Sample: capture a reproducible trace",
      "curl --trace-time --trace-ascii trace.txt URL",
      "Records a timestamped protocol trace for diagnosis without changing the request behavior.",
      "curl --trace-time --trace-ascii request.trace --request OPTIONS https://api.example.test/items",
      "Traces may contain tokens, cookies, and personal data. Redact them before sharing and delete the file after use.",
    ],
  ],
);

const sqlDefinition = definition(
  "sql",
  "SQL Developer Reference",
  "Portable SQL foundations, relational query design, transactions, performance, and practical reporting patterns.",
  ["SQL", "Database", "Query language"],
  "sql",
  [
    [
      "select",
      "Select columns",
      "SELECT id, name FROM users;",
      "Returns only the named columns from each matching row.",
      "SELECT id, name, created_at\nFROM users;",
    ],
    [
      "where",
      "Filter rows",
      "SELECT * FROM users WHERE active = TRUE;",
      "Applies a boolean predicate before rows are returned.",
      "SELECT id, email\nFROM users\nWHERE active = TRUE AND created_at >= DATE '2026-01-01';",
    ],
    [
      "order-limit",
      "Sort and limit results",
      "SELECT * FROM events ORDER BY occurred_at DESC LIMIT 20;",
      "Creates a deterministic result order and restricts the number of returned rows.",
      "SELECT id, type, occurred_at\nFROM events\nORDER BY occurred_at DESC, id DESC\nLIMIT 20;",
    ],
    [
      "null",
      "Handle NULL explicitly",
      "WHERE deleted_at IS NULL",
      "NULL represents missing or unknown data and must be tested with IS NULL or IS NOT NULL.",
      "SELECT id, title\nFROM tasks\nWHERE completed_at IS NULL;",
    ],
    [
      "aggregate",
      "Calculate aggregates",
      "SELECT COUNT(*), AVG(total) FROM orders;",
      "Reduces a set of rows to summary values such as counts, sums, minimums, and averages.",
      "SELECT COUNT(*) AS order_count, SUM(total) AS revenue\nFROM orders\nWHERE status = 'paid';",
    ],
    [
      "group",
      "Group before aggregating",
      "SELECT status, COUNT(*) FROM orders GROUP BY status;",
      "Creates one aggregate result per distinct grouping key.",
      "SELECT status, COUNT(*) AS orders\nFROM orders\nGROUP BY status\nORDER BY orders DESC;",
    ],
    [
      "join",
      "Join related tables",
      "SELECT ... FROM orders JOIN users ON users.id = orders.user_id;",
      "Combines rows through an explicit relationship instead of issuing repeated queries.",
      "SELECT orders.id, users.email, orders.total\nFROM orders\nJOIN users ON users.id = orders.user_id;",
    ],
    [
      "write",
      "Insert, update, and delete deliberately",
      "INSERT ...; UPDATE ... WHERE ...; DELETE ... WHERE ...;",
      "Changes relational data. A precise predicate and transaction protect against unintended broad changes.",
      "BEGIN;\nUPDATE tasks SET status = 'done' WHERE id = 42;\nSELECT id, status FROM tasks WHERE id = 42;\nCOMMIT;",
      "Preview the predicate with SELECT and use a transaction for consequential writes.",
    ],
  ],
  [
    [
      "transaction",
      "Use an explicit transaction",
      "BEGIN; ... COMMIT;",
      "Groups related changes so they succeed together or can be rolled back together.",
      "BEGIN;\nUPDATE accounts SET balance = balance - 50 WHERE id = 1;\nUPDATE accounts SET balance = balance + 50 WHERE id = 2;\nCOMMIT;",
    ],
    [
      "cte",
      "Name query stages with a CTE",
      "WITH recent AS (...) SELECT ... FROM recent;",
      "Makes a multi-stage query readable and lets later clauses reuse the named result.",
      "WITH recent AS (\n  SELECT * FROM orders WHERE created_at >= CURRENT_DATE - INTERVAL '7 days'\n)\nSELECT status, COUNT(*) FROM recent GROUP BY status;",
    ],
    [
      "window",
      "Calculate over a window",
      "SUM(total) OVER (PARTITION BY user_id ORDER BY created_at)",
      "Computes rankings or running values without collapsing detail rows.",
      "SELECT user_id, created_at, total,\n       SUM(total) OVER (PARTITION BY user_id ORDER BY created_at) AS running_total\nFROM orders;",
    ],
    [
      "exists",
      "Test related-row existence",
      "WHERE EXISTS (SELECT 1 FROM ...)",
      "Expresses a semi-join and can stop once the database finds one related row.",
      "SELECT u.id, u.email\nFROM users AS u\nWHERE EXISTS (SELECT 1 FROM orders AS o WHERE o.user_id = u.id);",
    ],
    [
      "explain",
      "Inspect an execution plan",
      "EXPLAIN ANALYZE SELECT ...;",
      "Shows the chosen plan and actual timing so optimization is based on evidence.",
      "EXPLAIN (ANALYZE, BUFFERS)\nSELECT * FROM orders WHERE user_id = 42 ORDER BY created_at DESC;",
      "ANALYZE executes the statement. Use plain EXPLAIN for writes unless execution is explicitly intended.",
    ],
    [
      "index",
      "Design an index for access patterns",
      "CREATE INDEX ... ON table (filter_column, sort_column);",
      "Supports frequent predicates and ordering when the measured plan justifies the storage and write cost.",
      "CREATE INDEX CONCURRENTLY orders_user_created_idx\nON orders (user_id, created_at DESC);",
    ],
  ],
  [
    [
      "sample-page",
      "Sample: stable keyset pagination",
      "WHERE (created_at, id) < (?, ?) ORDER BY created_at DESC, id DESC LIMIT 50",
      "Uses the final row as a cursor and avoids deep OFFSET scans.",
      "SELECT id, title, created_at\nFROM posts\nWHERE (created_at, id) < (TIMESTAMP '2026-07-01 10:00:00', 900)\nORDER BY created_at DESC, id DESC\nLIMIT 50;",
    ],
    [
      "sample-top",
      "Sample: top item per group",
      "ROW_NUMBER() OVER (PARTITION BY ... ORDER BY ...) = 1",
      "Ranks rows inside each group and selects the current winner.",
      "WITH ranked AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY created_at DESC) AS rn\n  FROM orders\n)\nSELECT * FROM ranked WHERE rn = 1;",
    ],
    [
      "sample-upsert",
      "Sample: idempotent upsert",
      "INSERT ... ON CONFLICT (...) DO UPDATE",
      "Creates a row or updates the existing row selected by a unique constraint.",
      "INSERT INTO settings (user_id, key, value)\nVALUES (42, 'theme', 'dark')\nON CONFLICT (user_id, key)\nDO UPDATE SET value = EXCLUDED.value;",
    ],
    [
      "sample-gaps",
      "Sample: find parents without children",
      "LEFT JOIN ... WHERE child.id IS NULL",
      "Uses an anti-join to identify missing related records.",
      "SELECT projects.id, projects.name\nFROM projects\nLEFT JOIN tasks ON tasks.project_id = projects.id\nWHERE tasks.id IS NULL;",
    ],
    [
      "sample-report",
      "Sample: monthly report",
      "DATE_TRUNC + GROUP BY",
      "Normalizes timestamps into reporting periods before aggregating.",
      "SELECT DATE_TRUNC('month', paid_at) AS month, SUM(total) AS revenue\nFROM orders\nWHERE status = 'paid'\nGROUP BY month\nORDER BY month;",
    ],
    [
      "sample-safe-delete",
      "Sample: verify a cleanup",
      "BEGIN; SELECT ...; DELETE ... RETURNING ...;",
      "Makes the affected set visible and returns deleted identifiers for verification before commit.",
      "BEGIN;\nSELECT id FROM sessions WHERE expires_at < CURRENT_TIMESTAMP;\nDELETE FROM sessions WHERE expires_at < CURRENT_TIMESTAMP RETURNING id;\nCOMMIT;",
      "Check the result count and backup policy before deleting production data.",
    ],
  ],
);

const regexDefinition = definition(
  "regex",
  "Regular Expressions Developer Reference",
  "Readable regular expressions, Unicode-aware matching, safe replacements, and practical parsing patterns.",
  ["Regex", "Text processing"],
  "regex",
  [
    [
      "literal",
      "Match literal text",
      "error",
      "Matches the exact character sequence with the engine's configured case rules.",
      "error",
    ],
    [
      "class",
      "Use character classes",
      "[A-F0-9]",
      "Matches one character from a set or range.",
      "#[A-Fa-f0-9]{6}",
    ],
    [
      "quantifier",
      "Repeat predictably",
      "a{2,4}",
      "Constrains how many times the preceding token may occur.",
      "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
    ],
    [
      "anchors",
      "Anchor the whole value",
      "^...$",
      "Requires a match at the start and end instead of accepting an arbitrary substring.",
      "^[a-z][a-z0-9_-]{2,31}$",
    ],
    [
      "groups",
      "Capture related text",
      "([a-z]+)-([0-9]+)",
      "Groups tokens and captures selected parts for extraction or replacement.",
      "^(?<name>[a-z]+)-(?<number>[0-9]+)$",
    ],
    [
      "alternation",
      "Choose alternatives",
      "cat|dog",
      "Matches one of several branches. Group alternatives when surrounding tokens apply to all branches.",
      "^(GET|POST|PATCH|DELETE)$",
    ],
    [
      "escape",
      "Escape metacharacters",
      "example\\.com",
      "A backslash turns a regex operator such as a dot into its literal character.",
      "^https://example\\.com/",
    ],
    [
      "flags",
      "Choose flags intentionally",
      "/pattern/giu",
      "Flags control case sensitivity, global iteration, multiline anchors, dot behavior, and Unicode handling.",
      "/straße/giu",
    ],
  ],
  [
    [
      "lookahead",
      "Require context with lookahead",
      "foo(?=bar)",
      "Matches only when the required context follows without consuming it.",
      "^(?=.*[A-Z])(?=.*[0-9]).{12,}$",
    ],
    [
      "lookbehind",
      "Require preceding context",
      "(?<=€)[0-9]+",
      "Matches based on preceding text when the target engine supports fixed or variable lookbehind.",
      "(?<=order-)[0-9]+",
    ],
    [
      "named",
      "Use named captures",
      "(?<year>[0-9]{4})",
      "Makes extracted values self-documenting and less dependent on capture order.",
      "^(?<year>[0-9]{4})-(?<month>[0-9]{2})-(?<day>[0-9]{2})$",
    ],
    [
      "backreference",
      "Require repeated captured text",
      "([a-z]+)\\s+\\1",
      "Matches text that repeats the exact value captured earlier.",
      "\\b(?<word>[A-Za-z]+)\\s+\\k<word>\\b",
    ],
    [
      "lazy",
      "Prefer the shortest match",
      ".*?",
      "A lazy quantifier stops at the earliest valid continuation instead of consuming as much as possible.",
      "<title>.*?</title>",
    ],
    [
      "unicode",
      "Match Unicode properties",
      "\\p{L}+",
      "Uses semantic Unicode categories for letters, numbers, scripts, and symbols.",
      "^[\\p{L}\\p{M}][\\p{L}\\p{M} '-]*$",
    ],
  ],
  [
    [
      "sample-log",
      "Sample: parse a log prefix",
      "^(?<date>\\d{4}-\\d{2}-\\d{2})T(?<time>\\d{2}:\\d{2}:\\d{2})Z \\[(?<level>[A-Z]+)\\]",
      "Extracts timestamp and severity from a stable log prefix.",
      "^(?<date>\\d{4}-\\d{2}-\\d{2})T(?<time>\\d{2}:\\d{2}:\\d{2})Z \\[(?<level>INFO|WARN|ERROR)\\]",
    ],
    [
      "sample-route",
      "Sample: extract route parameters",
      "^/users/(?<userId>[0-9]+)/posts/(?<postId>[0-9]+)$",
      "Accepts only the expected path shape and names both numeric identifiers.",
      "^/users/(?<userId>[0-9]+)/posts/(?<postId>[0-9]+)$",
    ],
    [
      "sample-replace",
      "Sample: reorder a name",
      "^(?<last>[^,]+),\\s*(?<first>.+)$",
      "Captures comma-separated name parts for a replacement such as first plus last.",
      "Pattern: ^(?<last>[^,]+),\\s*(?<first>.+)$\nReplacement: $<first> $<last>",
    ],
    [
      "sample-version",
      "Sample: validate a simple semantic version",
      "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$",
      "Checks the three numeric core components without pretending to implement the entire SemVer grammar.",
      "^(?<major>0|[1-9]\\d*)\\.(?<minor>0|[1-9]\\d*)\\.(?<patch>0|[1-9]\\d*)$",
    ],
    [
      "sample-whitespace",
      "Sample: normalize whitespace",
      "[\\t ]+",
      "Finds repeated horizontal whitespace so a replacement can collapse it to one space.",
      "Find: [\\t ]+\nReplace: single space",
    ],
    [
      "sample-email",
      "Sample: screen an email-shaped value",
      "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      "Catches obvious shape errors while leaving authoritative validation to confirmation mail and application rules.",
      "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      "Do not use a complex regex as proof that an address exists or can receive mail.",
    ],
  ],
);

const jqDefinition = definition(
  "jq",
  "jq Developer Reference",
  "Command-line JSON inspection, filtering, transformation, aggregation, and reliable automation.",
  ["jq", "JSON", "CLI"],
  "bash",
  [
    [
      "identity",
      "Pretty-print JSON",
      "jq . input.json",
      "Parses JSON and emits a normalized, readable representation.",
      "curl --silent https://api.example.test/items | jq .",
    ],
    [
      "field",
      "Select a field",
      "jq '.user.name' input.json",
      "Traverses object keys and returns the selected value or null when it is absent.",
      "jq '.repository.default_branch' repo.json",
    ],
    [
      "array",
      "Select an array element",
      "jq '.items[0]' input.json",
      "Uses zero-based indexing to select one array entry.",
      "jq '.events[-1]' events.json",
    ],
    [
      "iterate",
      "Iterate array values",
      "jq '.items[]' input.json",
      "Emits each array entry as a separate result for the next pipeline stage.",
      "jq '.users[] | .email' users.json",
    ],
    [
      "select",
      "Filter values",
      "jq '.items[] | select(.active == true)' input.json",
      "Keeps only inputs for which the predicate evaluates to true.",
      "jq '.items[] | select(.price > 20)' catalog.json",
    ],
    [
      "map",
      "Transform an array",
      "jq '.items | map(.name)' input.json",
      "Applies a filter to every entry and returns a new array.",
      "jq '.users | map({id, label: .name})' users.json",
    ],
    [
      "object",
      "Build a new object",
      "jq '{id, title: .name}' input.json",
      "Constructs an object with selected or renamed fields.",
      "jq '.items[] | {sku: .id, available: (.stock > 0)}' inventory.json",
    ],
    [
      "raw",
      "Emit raw strings",
      "jq -r '.token' input.json",
      "Writes string contents without JSON quotes, which is useful for controlled shell pipelines.",
      "jq -r '.artifacts[].url' release.json",
    ],
  ],
  [
    [
      "variable",
      "Bind a value",
      "jq '.threshold as $t | ...' input.json",
      "Names a value for reuse without repeating a long path.",
      "jq '.limit as $limit | .items[] | select(.score >= $limit)' scores.json",
    ],
    [
      "arg",
      "Pass external data safely",
      "jq --arg name \"$NAME\" '.name = $name' input.json",
      "Passes shell text as a JSON string without hand-built quoting.",
      "jq --arg version \"$VERSION\" '.release.version = $version' manifest.json",
    ],
    [
      "slurp",
      "Read multiple documents as an array",
      "jq --slurp '.' *.json",
      "Collects every parsed input document into one array.",
      "jq --slurp 'add' shard-*.json",
    ],
    [
      "group",
      "Group and aggregate",
      "jq 'sort_by(.team) | group_by(.team)' input.json",
      "Sorts by a key before grouping equal values for aggregation.",
      "jq 'sort_by(.status) | group_by(.status) | map({status: .[0].status, count: length})' jobs.json",
    ],
    [
      "reduce",
      "Reduce values",
      "jq 'reduce .items[] as $item (0; . + $item.total)' input.json",
      "Carries an accumulator through each selected input.",
      "jq 'reduce .orders[] as $order (0; . + $order.total)' report.json",
    ],
    [
      "exit",
      "Make filters control exit status",
      "jq --exit-status 'FILTER' input.json",
      "Returns a failing status when the final result is false or null, enabling CI assertions.",
      "jq --exit-status '.status == \"ready\"' deployment.json",
    ],
  ],
  [
    [
      "sample-api",
      "Sample: list failed API jobs",
      "jq -r '.jobs[] | select(.status == \"failed\") | .name'",
      "Filters failed jobs and prints one shell-friendly name per line.",
      "curl --silent https://api.example.test/jobs | jq -r '.jobs[] | select(.status == \"failed\") | .name'",
    ],
    [
      "sample-env",
      "Sample: create an environment map",
      "jq 'map({key: .name, value}) | from_entries'",
      "Transforms name/value records into a single lookup object.",
      "jq '.variables | map({key: .name, value: .value}) | from_entries' config.json",
    ],
    [
      "sample-merge",
      "Sample: merge configuration files",
      "jq --slurp '.[0] * .[1]' base.json override.json",
      "Recursively combines two objects with the later document taking precedence.",
      "jq --slurp '.[0] * .[1]' config.base.json config.production.json",
    ],
    [
      "sample-csv",
      "Sample: export selected fields as CSV",
      "jq -r '.items[] | [.id, .name, .status] | @csv'",
      "Produces correctly escaped CSV rows from selected fields.",
      "jq -r '.users[] | [.id, .email, .active] | @csv' users.json",
    ],
    [
      "sample-update",
      "Sample: update a matching item",
      "jq '(.items[] | select(.id == 42) | .active) = true'",
      "Changes only the selected nested value and emits the complete updated document.",
      "jq '(.items[] | select(.id == 42) | .active) = true' catalog.json",
    ],
    [
      "sample-redact",
      "Sample: redact sensitive fields",
      "jq 'walk(if type == \"object\" then del(.password, .token, .secret) else . end)'",
      "Removes known secret keys recursively before a controlled diagnostic export.",
      "jq 'walk(if type == \"object\" then del(.password, .access_token, .refresh_token) else . end)' response.json",
      "A denylist is not proof that all sensitive data is removed; inspect the result before sharing.",
    ],
  ],
);

const yamlDefinition = definition(
  "yaml",
  "YAML Developer Reference",
  "Readable YAML structures, anchors, schema pitfalls, validation, and common infrastructure examples.",
  ["YAML", "Configuration"],
  "yaml",
  [
    [
      "mapping",
      "Create a mapping",
      "name: api\nport: 8080",
      "Associates unique keys with scalar or nested values through indentation.",
      "service:\n  name: api\n  port: 8080",
    ],
    [
      "sequence",
      "Create a sequence",
      "ports:\n  - 80\n  - 443",
      "Represents an ordered list with one dash per item.",
      "environments:\n  - development\n  - staging\n  - production",
    ],
    [
      "nested",
      "Nest structures with spaces",
      "server:\n  tls:\n    enabled: true",
      "Indentation defines parent-child relationships; tabs are not valid indentation.",
      "database:\n  host: db.internal\n  pool:\n    min: 2\n    max: 10",
    ],
    [
      "quotes",
      "Quote ambiguous strings",
      'version: "1.0"',
      "Quotes preserve values that a schema might otherwise interpret as numbers, booleans, dates, or null.",
      'release: "2026-07-31"\nanswer: "yes"\ncode: "0012"',
    ],
    [
      "literal",
      "Use a literal block",
      "message: |\n  line one\n  line two",
      "The pipe preserves embedded line breaks and is suitable for scripts or certificates.",
      "script: |\n  set -eu\n  npm test\n  npm run build",
    ],
    [
      "folded",
      "Use a folded block",
      "summary: >\n  long text\n  on two lines",
      "The greater-than marker folds most source line breaks into spaces.",
      "description: >\n  This sentence stays readable in source\n  but becomes one logical line.",
    ],
    [
      "null-bool",
      "Represent booleans and null",
      "enabled: true\noptional: null",
      "Uses explicit lowercase booleans and null for portable, unsurprising configuration.",
      "features:\n  search: true\n  legacy: false\n  replacement: null",
    ],
    [
      "document",
      "Separate YAML documents",
      "---\nname: first\n---\nname: second",
      "Three dashes start a new document inside a multi-document stream.",
      "---\nkind: ConfigMap\nmetadata:\n  name: app\n---\nkind: Service\nmetadata:\n  name: app",
    ],
  ],
  [
    [
      "anchor",
      "Reuse a node with an anchor",
      "defaults: &defaults\n  retries: 3\njob:\n  <<: *defaults",
      "Anchors and aliases reuse parsed YAML nodes when the consuming tool supports merge keys.",
      "defaults: &defaults\n  timeout: 30\n  retries: 3\nworker:\n  <<: *defaults\n  retries: 5",
    ],
    [
      "flow",
      "Use flow style sparingly",
      "ports: [80, 443]",
      "Inline collections are compact for short values but become hard to review when nested.",
      "labels: { tier: api, environment: test }",
    ],
    [
      "schema",
      "Know the consumer schema",
      "replicas: 3",
      "YAML only provides syntax; Kubernetes, Compose, and CI systems each validate different keys and value types.",
      "service:\n  replicas: 3\n  image: example/app:1.2.0",
    ],
    [
      "variables",
      "Do not assume interpolation",
      'token: "${API_TOKEN}"',
      "Variable substitution is a feature of the consuming tool, not YAML itself.",
      'environment:\n  API_URL: "${API_URL}"',
    ],
    [
      "duplicates",
      "Reject duplicate keys",
      "name: first\nname: second",
      "Duplicate keys are ambiguous because parsers may reject them or silently keep one value.",
      "# Invalid and intentionally shown as a warning:\nname: first\nname: second",
      "Enable strict parsing or schema validation so duplicate keys fail before deployment.",
    ],
    [
      "validate",
      "Validate syntax and schema",
      "tool validate config.yaml",
      "Combines a YAML parser with the domain schema expected by the target system.",
      "docker compose -f compose.yaml config\nkubectl apply --dry-run=server -f deployment.yaml",
    ],
  ],
  [
    [
      "sample-app",
      "Sample: application configuration",
      "app:\n  port: 8080",
      "Keeps related values nested and gives ambiguous scalar values explicit types.",
      "app:\n  name: catalog\n  port: 8080\n  logLevel: info\ndatabase:\n  host: db.internal\n  ssl: true",
    ],
    [
      "sample-compose",
      "Sample: Compose service",
      "services:\n  web:\n    image: example/web:1.2.0",
      "Defines a pinned container image, port mapping, and explicit restart behavior.",
      'services:\n  web:\n    image: example/web:1.2.0\n    ports:\n      - "8080:3000"\n    restart: unless-stopped',
    ],
    [
      "sample-k8s",
      "Sample: Kubernetes ConfigMap",
      "apiVersion: v1\nkind: ConfigMap",
      "Stores non-secret configuration in a namespaced Kubernetes object.",
      "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: app-config\ndata:\n  LOG_LEVEL: info",
    ],
    [
      "sample-actions",
      "Sample: CI matrix",
      "strategy:\n  matrix:\n    node: [20, 22]",
      "Runs the same job for each declared runtime version.",
      "strategy:\n  fail-fast: false\n  matrix:\n    node: [20, 22]\nsteps:\n  - run: npm test",
    ],
    [
      "sample-anchor",
      "Sample: shared deployment defaults",
      "x-service: &service\n  restart: unless-stopped",
      "Uses an extension key and anchor to keep repeated service defaults in one place.",
      "x-service: &service\n  restart: unless-stopped\n  networks: [internal]\nservices:\n  api:\n    <<: *service\n    image: example/api:1.2.0",
    ],
    [
      "sample-secret",
      "Sample: reference a secret by name",
      "passwordPath: /run/secrets/db_password",
      "References a mounted secret without embedding its value in the YAML document.",
      "database:\n  user: app\n  passwordPath: /run/secrets/db_password",
      "Do not commit real passwords, tokens, private keys, or certificate keys into YAML files.",
    ],
  ],
);

const sshToolsDefinition = definition(
  "ssh-tools",
  "SSH, SCP & rsync Developer Reference",
  "Secure remote access, file transfer, tunnels, host configuration, and repeatable deployment workflows.",
  ["SSH", "SCP", "rsync", "Remote access"],
  "bash",
  [
    [
      "connect",
      "Connect to a host",
      "ssh user@host",
      "Starts an encrypted remote shell and verifies the host identity against known_hosts.",
      "ssh deploy@app.example.test",
    ],
    [
      "port",
      "Use a non-default port",
      "ssh -p 2222 user@host",
      "Connects to an SSH service listening on a custom TCP port.",
      "ssh -p 2222 deploy@app.example.test",
    ],
    [
      "keygen",
      "Create a modern key pair",
      "ssh-keygen -t ed25519 -a 64",
      "Creates a compact Ed25519 identity protected by a passphrase and stronger key derivation rounds.",
      "ssh-keygen -t ed25519 -a 64 -C 'ada@example.test'",
      "Protect private keys with a passphrase and never transmit them to the server.",
    ],
    [
      "config",
      "Name hosts in SSH config",
      "Host app-prod\n  HostName app.example.test\n  User deploy",
      "Moves stable connection options into ~/.ssh/config so commands and automation stay readable.",
      "Host app-prod\n  HostName app.example.test\n  User deploy\n  IdentityFile ~/.ssh/id_ed25519\n  IdentitiesOnly yes",
    ],
    [
      "remote",
      "Run one remote command",
      "ssh host command args",
      "Executes a command without starting an interactive shell and returns its exit status.",
      "ssh app-prod systemctl --user status catalog.service",
    ],
    [
      "scp",
      "Copy a file with SCP",
      "scp local.txt host:/remote/path/",
      "Transfers files over SSH with familiar copy semantics.",
      "scp ./release.tar.gz app-prod:/opt/catalog/incoming/",
    ],
    [
      "rsync",
      "Synchronize directories",
      "rsync -av SOURCE/ host:DEST/",
      "Copies changed files and preserves useful metadata while making source and destination slash semantics explicit.",
      "rsync -av --dry-run ./public/ app-prod:/opt/catalog/public/",
    ],
    [
      "agent",
      "Use an SSH agent",
      "ssh-add ~/.ssh/id_ed25519",
      "Keeps an unlocked private key in a user session so the key file is not repeatedly read by tools.",
      "ssh-add -l\nssh-add ~/.ssh/id_ed25519",
    ],
  ],
  [
    [
      "forward-local",
      "Create a local tunnel",
      "ssh -L 15432:db.internal:5432 bastion",
      "Makes a remote service available on a local loopback port through the SSH host.",
      "ssh -N -L 127.0.0.1:15432:db.internal:5432 bastion.example.test",
    ],
    [
      "forward-remote",
      "Create a remote tunnel",
      "ssh -R remote_port:local_host:local_port host",
      "Exposes a local service from the remote side when server policy permits it.",
      "ssh -N -R 127.0.0.1:19000:127.0.0.1:9000 app-prod",
      "Bind remote forwards to loopback unless wider exposure is explicitly required and protected.",
    ],
    [
      "jump",
      "Connect through a bastion",
      "ssh -J bastion target",
      "Uses ProxyJump to reach a private target without manually nesting shells.",
      "ssh -J ops@bastion.example.test deploy@10.0.2.15",
    ],
    [
      "multiplex",
      "Reuse SSH connections",
      "ControlMaster auto",
      "Keeps a protected control socket so repeated commands avoid a new handshake.",
      "Host app-*\n  ControlMaster auto\n  ControlPersist 5m\n  ControlPath ~/.ssh/control-%C",
    ],
    [
      "host-key",
      "Verify host keys",
      "ssh-keygen -F host",
      "Reads known_hosts entries and supports controlled replacement after an independently verified server key change.",
      "ssh-keygen -F app.example.test\nssh-keygen -lf host-key.pub",
      "Never delete a host-key warning merely to make it disappear; verify the new fingerprint through a trusted channel.",
    ],
    [
      "diagnose",
      "Diagnose connection selection",
      "ssh -G host\nssh -vv host",
      "Shows resolved configuration or a verbose handshake trace.",
      "ssh -G app-prod | less\nssh -vv app-prod",
      "Verbose output may reveal hostnames and user names; redact it before sharing.",
    ],
  ],
  [
    [
      "sample-deploy",
      "Sample: upload then activate a release",
      "scp artifact host:incoming && ssh host activate",
      "Separates transfer from a remote activation command and stops when upload fails.",
      "scp ./release.tar.gz app-prod:/opt/catalog/incoming/\nssh app-prod /opt/catalog/bin/activate-release release.tar.gz",
    ],
    [
      "sample-sync",
      "Sample: preview a static-site sync",
      "rsync --archive --delete --dry-run SOURCE/ host:DEST/",
      "Shows the exact additions, updates, and deletions before applying a mirror operation.",
      "rsync --archive --delete --itemize-changes --dry-run ./dist/ app-prod:/srv/www/catalog/",
      "Remove --dry-run only after reviewing the destination path and deletion list.",
    ],
    [
      "sample-db",
      "Sample: tunnel to a private database",
      "ssh -N -L local:db:5432 bastion",
      "Keeps the database private while exposing it only on local loopback.",
      "ssh -N -L 127.0.0.1:15432:db.internal:5432 bastion.example.test",
    ],
    [
      "sample-logs",
      "Sample: retrieve recent logs",
      "ssh host journalctl ... > local.log",
      "Runs filtering remotely and stores only the requested diagnostic window locally.",
      "ssh app-prod journalctl --user -u catalog.service --since '30 minutes ago' > catalog.log",
    ],
    [
      "sample-backup",
      "Sample: pull a backup safely",
      "rsync -av host:/backups/file.dump ./backups/",
      "Copies a named immutable backup into a local protected directory.",
      "rsync -av --partial app-prod:/opt/catalog/backups/catalog-20260731.dump ./backups/",
    ],
    [
      "sample-checksum",
      "Sample: verify transferred content",
      "sha256sum FILE",
      "Compares a cryptographic digest at both ends to detect transfer corruption.",
      "sha256sum release.tar.gz\nssh app-prod sha256sum /opt/catalog/incoming/release.tar.gz",
    ],
  ],
);

const packageManagersDefinition = definition(
  "node-package-managers",
  "npm, pnpm & Yarn Developer Reference",
  "Node.js dependency management, scripts, lockfiles, workspaces, security, and reproducible publishing.",
  ["npm", "pnpm", "Yarn", "Node.js"],
  "bash",
  [
    [
      "init",
      "Create package metadata",
      "npm init\npnpm init\nyarn init",
      "Creates package.json so dependencies, scripts, engines, and package metadata can be versioned.",
      "pnpm init",
    ],
    [
      "install",
      "Install the locked dependency graph",
      "npm ci\npnpm install --frozen-lockfile\nyarn install --immutable",
      "Uses the committed lockfile and fails when package metadata disagrees with it.",
      "pnpm install --frozen-lockfile",
    ],
    [
      "add",
      "Add a runtime dependency",
      "npm install NAME\npnpm add NAME\nyarn add NAME",
      "Records a package needed by the application at runtime.",
      "pnpm add fastify",
    ],
    [
      "dev",
      "Add a development dependency",
      "npm install -D NAME\npnpm add -D NAME\nyarn add -D NAME",
      "Records tooling used for build, tests, linting, or local development.",
      "pnpm add -D vitest",
    ],
    [
      "remove",
      "Remove a dependency",
      "npm uninstall NAME\npnpm remove NAME\nyarn remove NAME",
      "Updates package.json, the lockfile, and installed dependency links together.",
      "pnpm remove deprecated-package",
    ],
    [
      "scripts",
      "Run package scripts",
      "npm run test\npnpm test\nyarn test",
      "Executes commands declared in package.json with local binaries on PATH.",
      "pnpm run build",
    ],
    [
      "inspect",
      "Inspect why a package is installed",
      "npm explain NAME\npnpm why NAME\nyarn why NAME",
      "Traces direct and transitive dependency relationships.",
      "pnpm why react",
    ],
    [
      "outdated",
      "Review available updates",
      "npm outdated\npnpm outdated\nyarn outdated",
      "Compares installed, wanted, and latest versions without automatically changing the graph.",
      "pnpm outdated --recursive",
    ],
  ],
  [
    [
      "workspaces",
      "Run across workspaces",
      "pnpm --recursive COMMAND",
      "Coordinates scripts across a monorepo while respecting dependency ordering.",
      "pnpm --recursive --if-present test",
    ],
    [
      "filter",
      "Target selected packages",
      "pnpm --filter SELECTOR COMMAND",
      "Limits an operation to a package, dependency closure, or changed workspace set.",
      "pnpm --filter @example/web... build",
    ],
    [
      "overrides",
      "Override a transitive version",
      "pnpm.overrides / overrides / resolutions",
      "Forces a reviewed dependency version when upstream constraints need a temporary security or compatibility correction.",
      "pnpm:\n  overrides:\n    vulnerable-package: 2.4.1",
    ],
    [
      "peer",
      "Understand peer dependencies",
      "peerDependencies",
      "Declares compatibility with a host package that the consuming project must provide.",
      '{\n  "peerDependencies": {\n    "react": "^19.0.0"\n  }\n}',
    ],
    [
      "corepack",
      "Pin the package-manager version",
      "corepack use pnpm@VERSION",
      "Records the expected tool version so CI and contributors resolve the same lockfile semantics.",
      "corepack use pnpm@10.33.0",
    ],
    [
      "publish",
      "Inspect before publishing",
      "npm pack --dry-run",
      "Shows the files and metadata that would enter a registry package.",
      "npm pack --dry-run\nnpm publish --provenance --access public",
      "Publishing is an external irreversible action. Verify package name, version, contents, account, and registry first.",
    ],
  ],
  [
    [
      "sample-clean",
      "Sample: reproduce a CI install",
      "pnpm install --frozen-lockfile",
      "Fails when a contributor changed package.json without updating the lockfile.",
      "corepack enable\npnpm install --frozen-lockfile\npnpm test\npnpm build",
    ],
    [
      "sample-workspace",
      "Sample: add a workspace dependency",
      "pnpm --filter APP add PACKAGE --workspace",
      "Links one local workspace package without resolving a registry copy.",
      "pnpm --filter @example/web add @example/design --workspace",
    ],
    [
      "sample-script",
      "Sample: forward script arguments",
      "pnpm test -- --runInBand",
      "Uses the double dash to pass remaining arguments to the package script.",
      "pnpm test -- --coverage",
    ],
    [
      "sample-audit",
      "Sample: review an audit finding",
      "pnpm audit",
      "Lists known advisories so the dependency path and available remediation can be evaluated.",
      "pnpm audit\npnpm why affected-package",
      "Do not apply force upgrades blindly; verify breaking changes and rerun the application test suite.",
    ],
    [
      "sample-dedupe",
      "Sample: inspect duplicates",
      "pnpm dedupe --check",
      "Checks whether compatible package versions can be consolidated without changing declared ranges.",
      "pnpm dedupe --check\npnpm list --depth 4",
    ],
    [
      "sample-cache",
      "Sample: cache the package store in CI",
      "pnpm store path",
      "Locates the content-addressed store while leaving node_modules links workspace-specific.",
      "STORE_PATH=$(pnpm store path)\nprintf '%s\\n' \"$STORE_PATH\"",
    ],
  ],
);

const linuxToolboxDefinition = definition(
  "linux-toolbox",
  "Linux Toolbox Developer Reference",
  "Files, processes, permissions, text pipelines, networking, storage, and practical server diagnostics.",
  ["Linux", "Shell", "Operations"],
  "bash",
  [
    [
      "navigate",
      "Inspect and navigate",
      "pwd\nls -la\ncd PATH",
      "Shows the current directory, lists entries including hidden metadata, and changes location.",
      "pwd\nls -lah\ncd /opt/example",
    ],
    [
      "copy-move",
      "Copy and move deliberately",
      "cp SOURCE DEST\nmv SOURCE DEST",
      "Copies content or renames and relocates it while making both paths explicit.",
      "cp --archive config config.backup\nmv release.tmp release.json",
    ],
    [
      "read",
      "Read text safely",
      "less FILE\nhead FILE\ntail FILE",
      "Views whole or partial files without loading a large document into an editor.",
      "tail --lines 100 --follow /var/log/example.log",
    ],
    [
      "find",
      "Find files by criteria",
      "find ROOT -type f -name PATTERN",
      "Searches a bounded directory tree by name, type, size, time, and other metadata.",
      "find ./src -type f -name '*.ts' -print",
    ],
    [
      "grep",
      "Search text recursively",
      "rg PATTERN PATH",
      "Searches matching lines quickly while respecting common ignore files.",
      "rg -n 'TODO|FIXME' src tests",
    ],
    [
      "permissions",
      "Inspect and change permissions",
      "stat FILE\nchmod MODE FILE",
      "Shows ownership and mode bits, then changes only the intended access rights.",
      "stat deploy.sh\nchmod u+x deploy.sh",
    ],
    [
      "process",
      "Inspect processes",
      "ps aux\ntop",
      "Shows process owners, resource use, and command lines for diagnosis.",
      "ps -eo pid,ppid,user,%cpu,%mem,command --sort=-%cpu | head",
    ],
    [
      "storage",
      "Inspect filesystem usage",
      "df -h\ndu -sh PATH",
      "Separates filesystem capacity from the space consumed by a selected directory tree.",
      "df -h /\ndu -sh /var/lib/example",
    ],
  ],
  [
    [
      "pipes",
      "Build observable pipelines",
      "producer | filter | consumer",
      "Connects standard output to standard input so each stage has one clear responsibility.",
      "journalctl -u example --since today | rg 'ERROR|WARN' | less",
    ],
    [
      "xargs",
      "Convert input into arguments",
      "find ... -print0 | xargs -0 COMMAND",
      "Uses NUL-delimited paths so spaces and newlines cannot split file names.",
      "find ./logs -type f -name '*.log' -print0 | xargs -0 wc -l",
    ],
    [
      "archive",
      "Create and inspect archives",
      "tar -czf archive.tar.gz DIR\ntar -tzf archive.tar.gz",
      "Packages a directory and lets you inspect names before extraction.",
      "tar -czf config-backup.tar.gz ./config\ntar -tzf config-backup.tar.gz",
    ],
    [
      "network",
      "Inspect listeners and clients",
      "ss -lntp\ncurl URL",
      "Shows listening TCP sockets and exercises an application endpoint separately.",
      "ss -lntp\ncurl --fail-with-body http://127.0.0.1:4000/health",
    ],
    [
      "open-files",
      "Find open files and ports",
      "lsof PATH\nlsof -iTCP:PORT",
      "Maps files or sockets to the processes currently holding them.",
      "lsof -nP -iTCP:4000 -sTCP:LISTEN",
    ],
    [
      "signals",
      "Stop a process gracefully",
      "kill -TERM PID",
      "Requests orderly shutdown so the process can flush work and release resources.",
      "kill -TERM 12345",
      "Verify the exact PID and prefer the service manager when it owns the process.",
    ],
  ],
  [
    [
      "sample-large",
      "Sample: find large files",
      "find PATH -type f -size +SIZE -print",
      "Locates large regular files inside an explicit scope before any cleanup decision.",
      "find /var/log/example -type f -size +100M -printf '%s %p\\n' | sort -n",
    ],
    [
      "sample-port",
      "Sample: diagnose a busy port",
      "ss -lntp | rg ':PORT'",
      "Identifies the listening process before configuration or termination changes.",
      "ss -lntp | rg ':8080'\nlsof -nP -iTCP:8080 -sTCP:LISTEN",
    ],
    [
      "sample-logs",
      "Sample: inspect service errors",
      "journalctl -u SERVICE --since TIME",
      "Restricts logs by unit and time window for a focused investigation.",
      "journalctl -u catalog.service --since '1 hour ago' --priority warning",
    ],
    [
      "sample-hash",
      "Sample: verify a download",
      "sha256sum FILE",
      "Computes a digest that can be compared with a trusted publisher value.",
      "sha256sum release.tar.gz",
    ],
    [
      "sample-owner",
      "Sample: audit writable files",
      "find ROOT -type f -perm /022 -print",
      "Lists files writable by group or others inside a bounded application directory.",
      "find /opt/catalog -xdev -type f -perm /022 -print",
    ],
    [
      "sample-backup",
      "Sample: create a dated configuration archive",
      "tar -czf BACKUP SOURCE",
      "Creates a recoverable snapshot before a risky configuration change.",
      "tar -czf catalog-config-20260731.tar.gz /etc/catalog\ntar -tzf catalog-config-20260731.tar.gz",
      "Store backups outside the directory being changed and test restoration.",
    ],
  ],
);

const githubActionsDefinition = definition(
  "github-actions",
  "GitHub Actions Developer Reference",
  "Workflow syntax, secure permissions, matrices, caching, artifacts, reusable automation, and practical CI/CD patterns.",
  ["GitHub Actions", "CI", "CD"],
  "yaml",
  [
    [
      "workflow",
      "Define a workflow",
      "name: CI\non: [push]",
      "Names an automation file and declares the repository events that start it.",
      "name: CI\non:\n  push:\n    branches: [main]",
    ],
    [
      "job",
      "Create a job",
      "jobs:\n  test:\n    runs-on: ubuntu-latest",
      "Groups steps on one runner and exposes a job result to dependencies.",
      "jobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm test",
    ],
    [
      "checkout",
      "Check out repository content",
      "uses: actions/checkout@v4",
      "Makes the reviewed commit available in the runner workspace.",
      "steps:\n  - uses: actions/checkout@v4",
    ],
    [
      "setup",
      "Install a runtime",
      "uses: actions/setup-node@v4",
      "Configures a selected runtime version and can integrate dependency caching.",
      "- uses: actions/setup-node@v4\n  with:\n    node-version: 22\n    cache: pnpm",
    ],
    [
      "env",
      "Set environment values",
      "env:\n  NODE_ENV: test",
      "Defines non-secret values at workflow, job, or step scope.",
      "jobs:\n  test:\n    env:\n      NODE_ENV: test",
    ],
    [
      "secret",
      "Reference a repository secret",
      "${{ secrets.API_TOKEN }}",
      "Injects a configured secret at runtime without storing it in the workflow file.",
      "env:\n  API_TOKEN: ${{ secrets.API_TOKEN }}",
      "Do not print secrets, pass untrusted input into shell code, or expose secrets to untrusted pull requests.",
    ],
    [
      "artifact",
      "Upload build artifacts",
      "uses: actions/upload-artifact@v4",
      "Stores selected output from one job for inspection or later jobs.",
      "- uses: actions/upload-artifact@v4\n  with:\n    name: web-dist\n    path: dist/",
    ],
    [
      "needs",
      "Order dependent jobs",
      "deploy:\n  needs: test",
      "Runs a job only after its prerequisites complete successfully unless an explicit condition says otherwise.",
      "deploy:\n  needs: [lint, test, build]\n  runs-on: ubuntu-latest",
    ],
  ],
  [
    [
      "permissions",
      "Use least-privilege token permissions",
      "permissions:\n  contents: read",
      "Reduces what the automatic GITHUB_TOKEN can do if a step is compromised.",
      "permissions:\n  contents: read\n  pull-requests: read",
    ],
    [
      "matrix",
      "Run a job matrix",
      "strategy:\n  matrix:\n    node: [20, 22]",
      "Expands one job definition across supported configurations.",
      "strategy:\n  fail-fast: false\n  matrix:\n    os: [ubuntu-latest, windows-latest]\n    node: [20, 22]",
    ],
    [
      "concurrency",
      "Cancel stale runs",
      "concurrency:\n  group: ${{ github.workflow }}-${{ github.ref }}\n  cancel-in-progress: true",
      "Prevents obsolete branch runs from consuming runners or racing a newer deployment.",
      "concurrency:\n  group: deploy-${{ github.ref }}\n  cancel-in-progress: true",
    ],
    [
      "condition",
      "Guard a step or job",
      "if: github.ref == 'refs/heads/main'",
      "Evaluates an expression before allocating or executing the guarded work.",
      "if: github.event_name == 'push' && github.ref == 'refs/heads/main'",
    ],
    [
      "reusable",
      "Call a reusable workflow",
      "uses: org/repo/.github/workflows/build.yml@REF",
      "Centralizes reviewed automation behind explicit inputs, secrets, and a pinned ref.",
      "jobs:\n  build:\n    uses: example/platform/.github/workflows/node-build.yml@v2\n    with:\n      node-version: 22",
    ],
    [
      "oidc",
      "Prefer short-lived cloud identity",
      "permissions:\n  id-token: write",
      "Lets a trusted job exchange an OIDC assertion for short-lived cloud credentials instead of storing a long-lived key.",
      "permissions:\n  contents: read\n  id-token: write",
      "Restrict the cloud trust policy by repository, branch or environment, and workflow identity.",
    ],
  ],
  [
    [
      "sample-node",
      "Sample: Node.js CI",
      "checkout → setup-node → install → test",
      "Runs a reproducible locked install and the project checks on every pull request.",
      "name: CI\non: [pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n          cache: pnpm\n      - run: corepack enable\n      - run: pnpm install --frozen-lockfile\n      - run: pnpm test",
    ],
    [
      "sample-cache",
      "Sample: cache pnpm dependencies",
      "setup-node cache: pnpm",
      "Uses the lockfile as part of the managed dependency-cache key.",
      "- uses: actions/setup-node@v4\n  with:\n    node-version: 22\n    cache: pnpm\n- run: corepack enable\n- run: pnpm install --frozen-lockfile",
    ],
    [
      "sample-container",
      "Sample: build a container without publishing",
      "docker build --tag app:test .",
      "Verifies that the reviewed source produces a container image while keeping the job free of registry credentials.",
      "- name: Build image\n  run: docker build --tag example/app:test .",
    ],
    [
      "sample-release",
      "Sample: attach a reviewed artifact",
      "upload-artifact",
      "Carries the exact build output into a later protected release job.",
      "- uses: actions/upload-artifact@v4\n  with:\n    name: release-${{ github.sha }}\n    path: dist/\n    if-no-files-found: error",
    ],
    [
      "sample-environment",
      "Sample: protect production deployment",
      "environment: production",
      "Applies the repository environment's reviewers, branch rules, and scoped secrets.",
      "deploy:\n  needs: test\n  environment: production\n  runs-on: ubuntu-latest\n  steps:\n    - run: ./deploy-reviewed-commit.sh",
    ],
    [
      "sample-monorepo",
      "Sample: skip unrelated paths",
      "on:\n  pull_request:\n    paths: [...]",
      "Starts a workflow only when relevant files or shared configuration change.",
      "on:\n  pull_request:\n    paths:\n      - 'apps/web/**'\n      - 'packages/**'\n      - 'pnpm-lock.yaml'",
    ],
  ],
);

const postgresqlDefinition = definition(
  "postgresql",
  "PostgreSQL Developer Reference",
  "psql navigation, PostgreSQL SQL features, indexing, maintenance, backup, and production diagnostics.",
  ["PostgreSQL", "Database", "psql"],
  "sql",
  [
    [
      "connect",
      "Connect with psql",
      "psql --host HOST --username USER --dbname DB",
      "Starts a PostgreSQL session using explicit connection parameters.",
      "psql --host 127.0.0.1 --port 5432 --username app --dbname catalog",
      "Prefer a protected password file or secret provider over putting credentials in the command line or URI.",
    ],
    [
      "list-db",
      "List databases",
      "\\l",
      "Shows databases, owners, encodings, and access privileges inside psql.",
      "\\l+",
    ],
    [
      "list-table",
      "List relations",
      "\\dt",
      "Shows tables visible in the current schema search path.",
      "\\dt public.*",
    ],
    [
      "describe",
      "Describe a relation",
      "\\d+ public.orders",
      "Displays columns, types, indexes, constraints, storage, and other relation details.",
      "\\d+ public.orders",
    ],
    [
      "schema",
      "Use explicit schemas",
      "SELECT * FROM app.orders;",
      "Avoids ambiguity and keeps application objects separate from extensions or other tenants.",
      "CREATE SCHEMA IF NOT EXISTS app;\nSELECT id, status FROM app.orders;",
    ],
    [
      "identity",
      "Create generated identifiers",
      "id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY",
      "Uses PostgreSQL identity semantics instead of manually coordinating a sequence.",
      "CREATE TABLE app.jobs (\n  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  name TEXT NOT NULL\n);",
    ],
    [
      "returning",
      "Return changed rows",
      "INSERT ... RETURNING id;",
      "Returns server-generated or updated values without a follow-up query.",
      "INSERT INTO app.jobs (name) VALUES ('build') RETURNING id, name;",
    ],
    [
      "copy",
      "Import or export tabular data",
      "\\copy (...) TO 'file.csv' CSV HEADER",
      "Transfers data through the psql client, avoiding server filesystem access.",
      "\\copy (SELECT id, email FROM app.users ORDER BY id) TO 'users.csv' CSV HEADER",
      "Exports may contain personal data. Use an approved destination, retention period, and access controls.",
    ],
  ],
  [
    [
      "explain",
      "Read plans with buffers",
      "EXPLAIN (ANALYZE, BUFFERS) SELECT ...;",
      "Compares estimates with actual work and reveals cache and disk pressure.",
      "EXPLAIN (ANALYZE, BUFFERS)\nSELECT * FROM app.orders WHERE customer_id = 42 ORDER BY created_at DESC LIMIT 20;",
    ],
    [
      "index",
      "Create an online index",
      "CREATE INDEX CONCURRENTLY name ON table (...);",
      "Builds an index without blocking ordinary writes, with PostgreSQL restrictions around transaction blocks.",
      "CREATE INDEX CONCURRENTLY orders_customer_created_idx\nON app.orders (customer_id, created_at DESC);",
    ],
    [
      "locks",
      "Inspect blocking sessions",
      "SELECT ... FROM pg_stat_activity JOIN pg_locks ...",
      "Correlates active sessions and locks to explain waiting work before taking action.",
      "SELECT pid, wait_event_type, wait_event, state, query\nFROM pg_stat_activity\nWHERE datname = current_database() AND pid <> pg_backend_pid();",
    ],
    [
      "jsonb",
      "Query JSONB with indexes in mind",
      'payload @> \'{"status":"ready"}\'::jsonb',
      "Uses containment operators that can be supported by a GIN index.",
      'SELECT id FROM app.events\nWHERE payload @> \'{"status":"ready"}\'::jsonb;',
    ],
    [
      "vacuum",
      "Understand vacuum and analyze",
      "VACUUM (ANALYZE) table;",
      "Reclaims reusable tuple space and refreshes planner statistics; autovacuum normally performs this continuously.",
      "VACUUM (ANALYZE, VERBOSE) app.orders;",
      "Do not run aggressive maintenance blindly on a busy production table; inspect autovacuum and workload first.",
    ],
    [
      "isolation",
      "Choose transaction isolation deliberately",
      "BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;",
      "Controls which concurrent changes a transaction can observe and which anomalies PostgreSQL prevents.",
      "BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;\nSELECT SUM(total) FROM app.orders;\nCOMMIT;",
    ],
  ],
  [
    [
      "sample-backup",
      "Sample: create a custom-format backup",
      "pg_dump --format=custom --file=backup.dump DB",
      "Creates a compressed archive that pg_restore can inspect and selectively restore.",
      "pg_dump --host 127.0.0.1 --username app --format=custom --file=catalog.dump catalog",
      "Encrypt and access-control backups, verify they are non-empty, and test restoration regularly.",
    ],
    [
      "sample-restore",
      "Sample: rehearse a restore",
      "createdb RESTORE_DB\npg_restore --dbname RESTORE_DB backup.dump",
      "Restores into a separate database so integrity can be tested without overwriting production.",
      "createdb catalog_restore_test\npg_restore --exit-on-error --dbname catalog_restore_test catalog.dump\npsql --dbname catalog_restore_test --command 'SELECT COUNT(*) FROM app.orders;'",
    ],
    [
      "sample-size",
      "Sample: find large relations",
      "pg_total_relation_size",
      "Ranks tables and their indexes by total on-disk size.",
      "SELECT relname, pg_size_pretty(pg_total_relation_size(relid)) AS total_size\nFROM pg_catalog.pg_statio_user_tables\nORDER BY pg_total_relation_size(relid) DESC\nLIMIT 20;",
    ],
    [
      "sample-slow",
      "Sample: inspect current long-running queries",
      "pg_stat_activity",
      "Finds active sessions older than a chosen threshold without terminating them.",
      "SELECT pid, now() - query_start AS age, state, query\nFROM pg_stat_activity\nWHERE state <> 'idle' AND query_start < now() - INTERVAL '30 seconds'\nORDER BY query_start;",
    ],
    [
      "sample-duplicate",
      "Sample: find duplicate business keys",
      "GROUP BY ... HAVING COUNT(*) > 1",
      "Identifies duplicates before adding or repairing a unique constraint.",
      "SELECT lower(email) AS normalized_email, COUNT(*)\nFROM app.users\nGROUP BY lower(email)\nHAVING COUNT(*) > 1;",
    ],
    [
      "sample-batch",
      "Sample: claim queued work safely",
      "FOR UPDATE SKIP LOCKED",
      "Lets concurrent workers lock different queued rows without waiting on each other.",
      "WITH claimed AS (\n  SELECT id FROM app.jobs\n  WHERE status = 'queued'\n  ORDER BY created_at\n  FOR UPDATE SKIP LOCKED\n  LIMIT 10\n)\nUPDATE app.jobs SET status = 'running'\nWHERE id IN (SELECT id FROM claimed)\nRETURNING id;",
    ],
  ],
);

export const expandedDeveloperReferenceDefinitions: DeveloperReferenceDefinition[] =
  [
    httpCurlDefinition,
    sqlDefinition,
    regexDefinition,
    jqDefinition,
    yamlDefinition,
    sshToolsDefinition,
    packageManagersDefinition,
    linuxToolboxDefinition,
    githubActionsDefinition,
    postgresqlDefinition,
  ];
