import type {
  DeveloperReferenceDefinition,
  ReferenceCardSpec,
} from "./developer-reference-model.js";
import { referenceDeck as deck } from "./developer-reference-model.js";

const card = (
  key: string,
  title: string,
  command: string,
  explanation: string,
  example: string,
  exampleLanguage: ReferenceCardSpec["exampleLanguage"] = "bash",
  note?: string,
): ReferenceCardSpec => ({
  key,
  title,
  command,
  explanation,
  example,
  exampleLanguage,
  note,
});

const cmdDefinition: DeveloperReferenceDefinition = {
  id: "cmd",
  templateKey: "developer:cmd-reference:v1",
  title: "Windows CMD Reference",
  description:
    "Everyday Command Prompt operations, batch scripting techniques, and practical Windows workflows.",
  tags: ["CMD", "Windows", "Batch", "Developer reference"],
  decks: [
    deck(
      "introduction",
      "01 · CMD Introduction",
      "The small daily command set that covers most Command Prompt work.",
      [
        card(
          "help",
          "Find command help",
          "help\n<command> /?",
          "Lists built-in commands or opens the detailed help for one command.",
          "help\ndir /?",
          "batch",
        ),
        card(
          "cd",
          "Change directory",
          "cd [/d] <path>",
          "Changes the current directory. /d also changes the drive.",
          "cd /d C:\\Projects\\app",
          "batch",
        ),
        card(
          "dir",
          "List files and directories",
          "dir [path] [/a] [/b]",
          "Lists directory entries; /a includes hidden items and /b produces a compact bare list.",
          "dir C:\\Logs\\*.log /a /o-d",
          "batch",
        ),
        card(
          "mkdir",
          "Create directories",
          "mkdir <path>",
          "Creates one or more directories, including missing intermediate directories.",
          "mkdir build\\reports",
          "batch",
        ),
        card(
          "copy-move",
          "Copy or move files",
          "copy <source> <target>\nmove <source> <target>",
          "Copies files or moves and renames files and directories.",
          "copy config.example.ini config.ini\nmove report.txt archive\\",
          "batch",
        ),
        card(
          "delete",
          "Delete files or empty directories",
          "del <file>\nrmdir <directory>",
          "Deletes files or removes directories; recursive options require extra care.",
          "del /p build\\old.log\nrmdir build\\empty",
          "batch",
          "Check the resolved path first. DEL and RMDIR do not use the Recycle Bin.",
        ),
        card(
          "type-more",
          "Read text files",
          "type <file>\nmore < <file>",
          "Prints a text file directly or one screen at a time.",
          "type README.txt\nmore < large.log",
          "batch",
        ),
        card(
          "echo",
          "Print text and control batch output",
          "echo <text>\necho on|off",
          "Prints a value; @echo off suppresses command echoing in batch files.",
          "@echo off\necho Building %CD%",
          "batch",
        ),
        card(
          "redirect",
          "Redirect output",
          "command > file\ncommand >> file\ncommand 2> errors.log",
          "Writes standard output or errors to files; > replaces and >> appends.",
          "dir /b > files.txt\ntype missing.txt 2>> errors.log",
          "batch",
        ),
        card(
          "pipe-chain",
          "Pipe and conditionally chain commands",
          "command1 | command2\ncommand1 && command2\ncommand1 || command2",
          "Pipes text output or runs the next command only after success or failure.",
          "findstr /i error app.log && echo Errors found",
          "batch",
        ),
        card(
          "variables",
          "Use environment variables",
          "set NAME=value\necho %NAME%",
          "Sets a variable in the current CMD process and expands it with percent signs.",
          "set BUILD_DIR=%CD%\\build\necho %BUILD_DIR%",
          "batch",
        ),
        card(
          "where-findstr",
          "Locate commands and search text",
          "where <program>\nfindstr [options] <pattern> <files>",
          "Finds executables on PATH or matching lines in text files.",
          "where node\nfindstr /s /i /n TODO *.txt",
          "batch",
        ),
      ],
    ),
    deck(
      "advanced",
      "02 · CMD Advanced",
      "The less common batch features that complete the CMD toolbox.",
      [
        card(
          "setlocal",
          "Scope batch changes",
          "setlocal [EnableDelayedExpansion]\nendlocal",
          "Keeps environment and extension changes local to the current batch scope.",
          "setlocal\nset MODE=test\necho %MODE%\nendlocal",
          "batch",
        ),
        card(
          "if",
          "Branch on conditions",
          "if [not] <condition> (<commands>) else (<commands>)",
          "Branches on strings, file existence, numeric comparisons, or error levels.",
          "if exist package.json (echo Project found) else (exit /b 1)",
          "batch",
        ),
        card(
          "for",
          "Iterate over values and files",
          "for %%V in (<set>) do <command>",
          "Repeats a command for each value; interactive CMD uses one percent sign instead of two.",
          "for %%F in (*.log) do echo %%~nxF",
          "batch",
        ),
        card(
          "for-f",
          "Parse command or file output",
          'for /f "tokens=*" %%V in (<source>) do <command>',
          "Reads lines from a file, string, or command and splits them into tokens.",
          'for /f "delims=" %%L in (servers.txt) do echo Checking %%L',
          "batch",
        ),
        card(
          "call-label",
          "Call batch routines",
          "call :label [arguments]\ngoto :eof",
          "Calls a labeled subroutine and returns with GOTO :EOF.",
          "call :log Build started\nexit /b\n:log\necho [%date% %time%] %*\ngoto :eof",
          "batch",
        ),
        card(
          "pushd-popd",
          "Temporarily change location",
          "pushd <path>\npopd",
          "Saves the current directory, changes location, then restores it later.",
          "pushd \\server\\share\nbuild.cmd\npopd",
          "batch",
        ),
        card(
          "processes",
          "Inspect and stop processes",
          "tasklist\ntaskkill /pid <pid>",
          "Lists running processes and requests that a selected process end.",
          'tasklist /fi "IMAGENAME eq node.exe"\ntaskkill /pid 4242',
          "batch",
          "Confirm the PID and omit /f unless graceful termination has failed.",
        ),
        card(
          "robocopy",
          "Synchronize directory trees",
          "robocopy <source> <target> [files] [options]",
          "Copies directory trees with retry, logging, and restart support; exit codes 0 through 7 can still indicate success.",
          "robocopy data backup /e /copy:DAT /r:2 /w:2 /log:backup.log",
          "batch",
          "Avoid /MIR or /PURGE until you have verified both paths because they can delete target files.",
        ),
      ],
    ),
    deck(
      "samples",
      "03 · CMD Practical Samples",
      "Ten ready-to-adapt Command Prompt and batch-file workflows.",
      [
        card(
          "sample-01",
          "Sample 1: Inspect a project folder",
          "cd /d C:\\Projects\\app && dir /a",
          "Moves to a project only if the path change succeeds, then lists all entries.",
          "cd /d C:\\Projects\\app && dir /a",
          "batch",
        ),
        card(
          "sample-02",
          "Sample 2: Create and copy build input",
          "mkdir build 2>nul & copy config.ini build\\",
          "Creates a target directory and copies a file into it.",
          "if not exist build mkdir build\ncopy /y config.ini build\\",
          "batch",
        ),
        card(
          "sample-03",
          "Sample 3: Search logs recursively",
          'findstr /s /i /n /c:"connection failed" logs\\*.log',
          "Searches all matching logs and includes file names and line numbers.",
          'findstr /s /i /n /c:"connection failed" logs\\*.log',
          "batch",
        ),
        card(
          "sample-04",
          "Sample 4: Capture output and errors",
          "build.cmd > build.log 2>&1",
          "Stores both standard output and standard error in one diagnostic log.",
          "call build.cmd > build.log 2>&1\nif errorlevel 1 type build.log",
          "batch",
        ),
        card(
          "sample-05",
          "Sample 5: Back up a directory",
          "robocopy src backup /e /r:2 /w:2",
          "Copies a complete tree without deleting unrelated target files.",
          "robocopy C:\\Projects\\app C:\\Backups\\app /e /copy:DAT /r:2 /w:2",
          "batch",
        ),
        card(
          "sample-06",
          "Sample 6: Require a tool",
          "where git >nul 2>&1 || exit /b 1",
          "Checks PATH and stops the batch file when a required executable is missing.",
          "where git >nul 2>&1 || (echo Git is required & exit /b 1)",
          "batch",
        ),
        card(
          "sample-07",
          "Sample 7: Scope temporary settings",
          "setlocal\nset NODE_ENV=test\ncall npm test\nendlocal",
          "Applies an environment value only to the batch scope.",
          "@echo off\nsetlocal\nset NODE_ENV=test\ncall npm test\nset RESULT=%ERRORLEVEL%\nendlocal & exit /b %RESULT%",
          "batch",
        ),
        card(
          "sample-08",
          "Sample 8: Process matching files",
          "for %%F in (*.json) do <command>",
          "Runs one command for every JSON file in the current directory.",
          "for %%F in (*.json) do echo Validating %%~nxF",
          "batch",
        ),
        card(
          "sample-09",
          "Sample 9: Preserve an exit code",
          "command\nset RESULT=%ERRORLEVEL%\nexit /b %RESULT%",
          "Captures a program result before another command overwrites ERRORLEVEL.",
          "call test.cmd\nset RESULT=%ERRORLEVEL%\necho Test exit: %RESULT%\nexit /b %RESULT%",
          "batch",
        ),
        card(
          "sample-10",
          "Sample 10: Run a tool and wait",
          'start "" /wait <program> [arguments]',
          "Starts a GUI or console program and waits for it to finish.",
          'start "" /wait notepad.exe README.txt\necho Editor closed',
          "batch",
        ),
      ],
    ),
  ],
};

const powershellDefinition: DeveloperReferenceDefinition = {
  id: "powershell",
  templateKey: "developer:powershell-reference:v1",
  title: "PowerShell Developer Reference",
  description:
    "Object-oriented shell basics, advanced automation, and practical cross-platform PowerShell workflows.",
  tags: ["PowerShell", "Automation", "Windows", "Developer reference"],
  decks: [
    deck(
      "introduction",
      "01 · PowerShell Introduction",
      "The cmdlets and object-pipeline concepts used in everyday PowerShell work.",
      [
        card(
          "help",
          "Discover commands and help",
          "Get-Command <pattern>\nGet-Help <command> -Examples",
          "Finds commands by name or capability and opens local help.",
          "Get-Command *Json*\nGet-Help ConvertTo-Json -Online",
          "powershell",
        ),
        card(
          "location",
          "Navigate locations",
          "Get-Location\nSet-Location <path>",
          "Shows or changes the current location; cd and pwd are aliases.",
          "Set-Location $HOME\nGet-Location",
          "powershell",
        ),
        card(
          "child-item",
          "List child items",
          "Get-ChildItem [path] [-Recurse]",
          "Returns file-system entries as objects rather than formatted text.",
          "Get-ChildItem ./src -File -Recurse",
          "powershell",
        ),
        card(
          "new-item",
          "Create files and directories",
          "New-Item -ItemType File|Directory -Path <path>",
          "Creates a typed item at an explicit path.",
          "New-Item -ItemType Directory -Path ./build -Force",
          "powershell",
        ),
        card(
          "copy-move-remove",
          "Copy, move, and remove items",
          "Copy-Item\nMove-Item\nRemove-Item",
          "Manipulates provider items with consistent parameter names.",
          "Copy-Item ./config.example.json ./config.json",
          "powershell",
          "Use -WhatIf before recursive or broad Remove-Item operations.",
        ),
        card(
          "content",
          "Read and write text",
          "Get-Content\nSet-Content\nAdd-Content",
          "Reads lines or writes and appends text using explicit encoding options.",
          "Get-Content ./app.log -Tail 20\n'finished' | Add-Content ./app.log",
          "powershell",
        ),
        card(
          "pipeline",
          "Pass objects through a pipeline",
          "command | command",
          "Passes .NET objects with properties and types, not only display text.",
          "Get-Process | Select-Object Name, CPU",
          "powershell",
        ),
        card(
          "where",
          "Filter objects",
          "Where-Object <condition>",
          "Keeps objects whose script-block condition evaluates to true.",
          "Get-ChildItem -File | Where-Object Length -gt 1MB",
          "powershell",
        ),
        card(
          "select-sort",
          "Shape and sort results",
          "Select-Object\nSort-Object",
          "Chooses properties, computes fields, limits rows, and sorts objects.",
          "Get-Process | Sort-Object CPU -Descending | Select-Object -First 5 Name, CPU",
          "powershell",
        ),
        card(
          "variables",
          "Create variables and interpolate",
          '$name = <value>\n"Value: $name"',
          "Stores any PowerShell object; double quotes expand values and single quotes remain literal.",
          "$project = 'Flash-n-Flip'\n\"Building $project\"",
          "powershell",
        ),
        card(
          "environment",
          "Read and set environment values",
          "$env:NAME\n$env:NAME = <value>",
          "Accesses the current process environment through the Env provider.",
          "$env:NODE_ENV = 'test'\nnpm test",
          "powershell",
        ),
        card(
          "test-path",
          "Test whether a path exists",
          "Test-Path <path>",
          "Returns a Boolean and can distinguish leaf files from containers.",
          "if (Test-Path ./package.json -PathType Leaf) { 'Project found' }",
          "powershell",
        ),
      ],
    ),
    deck(
      "advanced",
      "02 · PowerShell Advanced",
      "Functions, error handling, remoting, modules, and safe automation controls.",
      [
        card(
          "functions",
          "Define parameterized functions",
          "function Name { param(...) ... }",
          "Packages reusable logic with typed parameters and standard validation.",
          'function Get-Greeting { param([Parameter(Mandatory)][string]$Name) "Hello, $Name" }',
          "powershell",
        ),
        card(
          "errors",
          "Handle terminating errors",
          "try { ... } catch { ... } finally { ... }",
          "Handles exceptions; -ErrorAction Stop converts many non-terminating errors into catchable ones.",
          "try { Get-Content missing.txt -ErrorAction Stop } catch { Write-Error $_ }",
          "powershell",
        ),
        card(
          "modules",
          "Work with modules",
          "Get-Module -ListAvailable\nImport-Module <name>",
          "Discovers and loads reusable command packages.",
          "Get-Module -ListAvailable | Sort-Object Name\nImport-Module Microsoft.PowerShell.Management",
          "powershell",
        ),
        card(
          "remoting",
          "Run commands remotely",
          "Invoke-Command -ComputerName <host> -ScriptBlock { ... }",
          "Runs a script block through a configured PowerShell remoting endpoint.",
          "Invoke-Command -ComputerName app01 -ScriptBlock { Get-Service }",
          "powershell",
          "Use authenticated, trusted remoting endpoints and least-privilege identities.",
        ),
        card(
          "jobs",
          "Run background jobs",
          "Start-Job\nReceive-Job\nRemove-Job",
          "Runs work asynchronously and later retrieves its serialized output.",
          "$job = Start-Job { Get-ChildItem / -ErrorAction SilentlyContinue }\nReceive-Job $job -Wait -AutoRemoveJob",
          "powershell",
        ),
        card(
          "cim",
          "Query system management data",
          "Get-CimInstance -ClassName <class>",
          "Retrieves structured management information locally or through CIM sessions.",
          "Get-CimInstance Win32_OperatingSystem | Select-Object Caption, LastBootUpTime",
          "powershell",
        ),
        card(
          "json",
          "Convert structured JSON",
          "ConvertFrom-Json\nConvertTo-Json",
          "Maps JSON to PowerShell objects and back; -Depth matters for nested output.",
          "$config = Get-Content config.json -Raw | ConvertFrom-Json\n$config | ConvertTo-Json -Depth 10",
          "powershell",
        ),
        card(
          "safety",
          "Preview and confirm changes",
          "command -WhatIf\ncommand -Confirm",
          "Uses ShouldProcess-enabled cmdlets to show planned mutations or request confirmation.",
          "Get-ChildItem ./tmp -File | Remove-Item -WhatIf",
          "powershell",
          "Execution policy is not a security boundary; prefer signed, reviewed scripts and normal OS access controls.",
        ),
      ],
    ),
    deck(
      "samples",
      "03 · PowerShell Practical Samples",
      "Ten reusable object-pipeline and automation workflows.",
      [
        card(
          "sample-01",
          "Sample 1: Inventory large files",
          "Get-ChildItem ... | Where-Object ... | Sort-Object ...",
          "Builds a readable list from file objects without parsing formatted text.",
          "Get-ChildItem ./data -File -Recurse | Where-Object Length -gt 10MB | Sort-Object Length -Descending | Select-Object FullName, Length",
          "powershell",
        ),
        card(
          "sample-02",
          "Sample 2: Export process data to CSV",
          "... | Export-Csv -NoTypeInformation",
          "Serializes selected object properties into a portable CSV file.",
          "Get-Process | Select-Object Name, Id, CPU | Export-Csv ./processes.csv -NoTypeInformation",
          "powershell",
        ),
        card(
          "sample-03",
          "Sample 3: Read and filter CSV data",
          "Import-Csv <file> | Where-Object ...",
          "Turns CSV rows into objects that can be filtered by named columns.",
          "Import-Csv ./users.csv | Where-Object Status -eq 'active' | Select-Object Email",
          "powershell",
        ),
        card(
          "sample-04",
          "Sample 4: Call a JSON API",
          "Invoke-RestMethod -Uri <uri>",
          "Requests an API and converts a JSON response into objects.",
          "$releases = Invoke-RestMethod 'https://api.example.test/releases'\n$releases | Select-Object -First 5 name",
          "powershell",
          "Do not place credentials in the URL or committed script; use protected secret sources.",
        ),
        card(
          "sample-05",
          "Sample 5: Follow a log",
          "Get-Content <file> -Tail <n> -Wait",
          "Prints recent lines and keeps waiting for appended content.",
          "Get-Content ./app.log -Tail 50 -Wait",
          "powershell",
        ),
        card(
          "sample-06",
          "Sample 6: Preview stale-file cleanup",
          "Get-ChildItem ... | Remove-Item -WhatIf",
          "Selects old temporary files and previews every deletion.",
          "$cutoff = (Get-Date).AddDays(-30)\nGet-ChildItem ./tmp -File | Where-Object LastWriteTime -lt $cutoff | Remove-Item -WhatIf",
          "powershell",
        ),
        card(
          "sample-07",
          "Sample 7: Check a service",
          "Get-Service <name>",
          "Reads service state and starts it only when necessary.",
          "$service = Get-Service spooler\nif ($service.Status -ne 'Running') { Start-Service $service.Name -WhatIf }",
          "powershell",
        ),
        card(
          "sample-08",
          "Sample 8: Verify a downloaded file",
          "Get-FileHash <file> -Algorithm SHA256",
          "Computes a digest and compares it with a trusted published value.",
          "$actual = (Get-FileHash ./tool.zip -Algorithm SHA256).Hash\nif ($actual -ne $expected) { throw 'Checksum mismatch' }",
          "powershell",
        ),
        card(
          "sample-09",
          "Sample 9: Run independent jobs",
          "Start-Job ...; Receive-Job ...",
          "Starts independent tasks and waits for their results together.",
          "$jobs = 'app01','app02' | ForEach-Object { Start-Job -ArgumentList $_ -ScriptBlock { param($h) Test-Connection $h -Count 1 } }\n$jobs | Receive-Job -Wait -AutoRemoveJob",
          "powershell",
        ),
        card(
          "sample-10",
          "Sample 10: Build a reusable script",
          "param(...)\nSet-StrictMode -Version Latest",
          "Creates a script with explicit input, strict variable checks, and failure handling.",
          "param([Parameter(Mandatory)][string]$Path)\nSet-StrictMode -Version Latest\n$ErrorActionPreference = 'Stop'\nGet-ChildItem -LiteralPath $Path",
          "powershell",
        ),
      ],
    ),
  ],
};

const bashZshDefinition: DeveloperReferenceDefinition = {
  id: "bash-zsh",
  templateKey: "developer:bash-zsh-reference:v1",
  title: "Bash & Zsh Reference",
  description:
    "Shared shell fundamentals, explicit Bash/Zsh differences, and portable command-line workflows.",
  tags: ["Bash", "Zsh", "Shell", "Developer reference"],
  decks: [
    deck(
      "introduction",
      "01 · Bash & Zsh Introduction",
      "The everyday syntax shared by Bash and Zsh, with portability boundaries called out.",
      [
        card(
          "navigation",
          "Navigate and inspect locations",
          "pwd\ncd <directory>\nls -la",
          "Prints the working directory, changes it, and lists visible and hidden entries.",
          "cd ~/projects/app\npwd\nls -la",
        ),
        card(
          "files",
          "Create, copy, move, and remove",
          "mkdir\ntouch\ncp\nmv\nrm",
          "Manipulates files and directories with standard Unix tools.",
          "mkdir -p build/reports\ncp config.example.json build/config.json",
          "bash",
          "Quote paths and inspect targets before rm; removal normally bypasses a desktop trash folder.",
        ),
        card(
          "globs",
          "Match file names with globs",
          "*  ?  [abc]",
          "Expands patterns to path names before a command runs.",
          "printf '%s\\n' ./*.json",
          "bash",
          "An unmatched glob remains literal in default Bash but raises nomatch in default Zsh.",
        ),
        card(
          "variables",
          "Assign and expand variables",
          "name=value\nprintf '%s\\n' \"$name\"",
          "Assignments have no spaces around =; quoted expansion preserves each value as one argument.",
          "project='Flash-n-Flip'\nprintf 'Building %s\\n' \"$project\"",
        ),
        card(
          "quotes",
          "Choose shell quoting",
          "'literal'\n\"expand $value\"\n\\escape",
          "Single quotes are literal; double quotes allow parameter and command expansion.",
          "file='Quarterly report.txt'\nwc -l -- \"$file\"",
        ),
        card(
          "redirect",
          "Redirect streams",
          "command > file\ncommand >> file\ncommand 2> errors.log",
          "Replaces or appends standard output and separately captures standard error.",
          "npm test > test.log 2>&1",
        ),
        card(
          "pipes",
          "Connect commands with pipes",
          "command1 | command2",
          "Sends one program's standard output to the next program's standard input.",
          "printf '%s\\n' ./*.log | sort | head",
        ),
        card(
          "search",
          "Search text and paths",
          "grep [options] <pattern> <files>\nfind <path> <tests>",
          "Finds matching lines or walks directory trees by metadata.",
          "grep -RIn --exclude-dir=.git 'TODO' .\nfind . -type f -name '*.json'",
        ),
        card(
          "conditions",
          "Test and branch",
          "if [[ condition ]]; then ...; fi",
          "Runs commands conditionally. Double brackets are supported by both Bash and Zsh but are not POSIX sh syntax.",
          "if [[ -f package.json ]]; then printf '%s\\n' 'Project found'; fi",
        ),
        card(
          "loops",
          "Loop over arguments",
          'for item in "$@"; do ...; done',
          "Processes every positional argument while preserving spaces.",
          'for file in "$@"; do printf \'%s\\n\' "$file"; done',
        ),
        card(
          "functions",
          "Define shell functions",
          "name() { commands; }",
          "Creates a reusable command in the current shell; arguments appear as $1, $2, and $@.",
          "greet() { printf 'Hello, %s\\n' \"$1\"; }\ngreet Ada",
        ),
        card(
          "status-chain",
          "React to command status",
          "command && on_success\ncommand || on_failure\nprintf '%s\\n' \"$?\"",
          "Zero means success; && and || conditionally run the next list.",
          "npm test && printf '%s\\n' 'Tests passed' || printf '%s\\n' 'Tests failed'",
        ),
      ],
    ),
    deck(
      "advanced",
      "02 · Bash & Zsh Advanced",
      "Eight important differences to prevent scripts and interactive configuration from behaving unexpectedly.",
      [
        card(
          "startup-files",
          "Difference 1: Startup files",
          "Bash: ~/.bash_profile, ~/.bashrc\nZsh: ~/.zprofile, ~/.zshrc",
          "Login and interactive shells load different files. Put interactive aliases and completion in the shell's rc file.",
          "# Bash interactive: ~/.bashrc\n# Zsh interactive: ~/.zshrc",
        ),
        card(
          "arrays",
          "Difference 2: Array indexes",
          "Bash: ${items[0]}\nZsh: ${items[1]}",
          "Bash arrays are zero-based; Zsh arrays are one-based by default unless an option changes behavior.",
          '# Bash\nitems=(alpha beta); printf \'%s\\n\' "${items[0]}"\n# Zsh\nitems=(alpha beta); print -r -- "${items[1]}"',
        ),
        card(
          "unmatched-globs",
          "Difference 3: Unmatched globs",
          "Bash: pattern stays literal by default\nZsh: nomatch error by default",
          "Zsh stops before running the command when a glob has no matches; Bash usually passes the pattern unchanged.",
          "# Portable intent: test for files explicitly\nfind . -maxdepth 1 -type f -name '*.log' -print",
        ),
        card(
          "options",
          "Difference 4: Shell options",
          "Bash: shopt -s <option>\nZsh: setopt <option>",
          "The option names and configuration commands are shell-specific.",
          "# Bash\nshopt -s nullglob\n# Zsh\nsetopt NULL_GLOB",
        ),
        card(
          "completion",
          "Difference 5: Completion systems",
          "Bash: complete / compgen\nZsh: autoload -Uz compinit && compinit",
          "Each shell has its own programmable completion framework and configuration.",
          "# Zsh startup\nautoload -Uz compinit\ncompinit",
        ),
        card(
          "prompt",
          "Difference 6: Prompt expansion",
          "Bash: PS1='\\u@\\h \\w $ '\nZsh: PROMPT='%n@%m %~ %# '",
          "Bash uses backslash escapes while Zsh uses percent escapes for common prompt fields.",
          "# Keep the matching line in ~/.bashrc or ~/.zshrc",
        ),
        card(
          "word-splitting",
          "Difference 7: Unquoted expansion",
          "Bash may split $value\nZsh normally does not split $value",
          "Default Zsh does not apply Bourne-style word splitting to unquoted parameters. Quote expansions in both shells for predictable arguments.",
          "value='two words'\nprintf '<%s>\\n' \"$value\"",
        ),
        card(
          "compatibility",
          "Difference 8: Interpreter contracts",
          "#!/usr/bin/env bash\n#!/usr/bin/env zsh\n#!/bin/sh",
          "The shebang selects the language. Zsh can emulate sh, but default interactive Zsh is not POSIX-compatible.",
          "#!/usr/bin/env bash\n# Bash features are now an explicit dependency.",
        ),
      ],
    ),
    deck(
      "samples",
      "03 · Bash & Zsh Practical Samples",
      "Ten workflows that make the interpreter and portability assumptions explicit.",
      [
        card(
          "sample-01",
          "Sample 1: Start an explicit Bash script",
          "#!/usr/bin/env bash",
          "Declares Bash as the interpreter instead of depending on the user's login shell.",
          "#!/usr/bin/env bash\nset -u\nprintf 'Running with Bash %s\\n' \"$BASH_VERSION\"",
        ),
        card(
          "sample-02",
          "Sample 2: Start an explicit Zsh script",
          "#!/usr/bin/env zsh",
          "Declares Zsh when the script intentionally uses Zsh syntax or glob qualifiers.",
          '#!/usr/bin/env zsh\nsetopt ERR_EXIT NO_UNSET\nprint -r -- "Running with Zsh $ZSH_VERSION"',
        ),
        card(
          "sample-03",
          "Sample 3: Clean up a temporary directory",
          "mktemp -d\ntrap '<cleanup>' EXIT",
          "Creates a unique temporary directory and schedules cleanup when the script exits.",
          "tmp_dir=$(mktemp -d) || exit 1\ntrap 'rm -rf -- \"$tmp_dir\"' EXIT\nprintf '%s\\n' \"$tmp_dir\"",
          "bash",
          "Keep the generated path quoted and never replace it with an unchecked or empty variable.",
        ),
        card(
          "sample-04",
          "Sample 4: Process file names safely",
          "find ... -print0 | while IFS= read -r -d '' file",
          "Uses NUL separators so spaces and newlines in file names do not split records.",
          "find . -type f -name '*.json' -print0 | while IFS= read -r -d '' file; do printf '%s\\n' \"$file\"; done",
        ),
        card(
          "sample-05",
          "Sample 5: Search source without dependencies",
          "find <path> -type f -exec grep ... {} +",
          "Combines standard find and grep without relying on a shell-specific recursive glob.",
          "find src -type f -name '*.ts' -exec grep -nH 'TODO' {} +",
        ),
        card(
          "sample-06",
          "Sample 6: Validate function arguments",
          "function_name() { [[ $# -eq n ]] || return 2; ...; }",
          "Checks the function contract before using positional parameters.",
          'copy_config() { [[ $# -eq 2 ]] || { printf \'usage: copy_config SRC DST\\n\' >&2; return 2; }; cp -- "$1" "$2"; }',
        ),
        card(
          "sample-07",
          "Sample 7: Detect Bash or Zsh",
          "[[ -n ${BASH_VERSION:-} ]]\n[[ -n ${ZSH_VERSION:-} ]]",
          "Uses shell-specific version variables instead of the unreliable $SHELL preference variable.",
          "if [[ -n ${BASH_VERSION:-} ]]; then echo Bash; elif [[ -n ${ZSH_VERSION:-} ]]; then echo Zsh; else echo Other; fi",
        ),
        card(
          "sample-08",
          "Sample 8: Add one directory to PATH",
          'export PATH="$HOME/.local/bin:$PATH"',
          "Prepends a user tool directory for the current process and its children.",
          'case :$PATH: in *:"$HOME/.local/bin":*) ;; *) export PATH="$HOME/.local/bin:$PATH" ;; esac',
        ),
        card(
          "sample-09",
          "Sample 9: Configure the matching prompt",
          "PS1=...\nPROMPT=...",
          "Keeps shell-specific prompt syntax in the corresponding rc file.",
          "# ~/.bashrc\nPS1='\\u@\\h \\w $ '\n# ~/.zshrc\nPROMPT='%n@%m %~ %# '",
        ),
        card(
          "sample-10",
          "Sample 10: Run Bash code from Zsh",
          "bash path/to/file.bash [arguments]",
          "Invokes the required interpreter explicitly, so the caller's Zsh options cannot reinterpret the script.",
          "bash ./scripts/build.bash --production",
        ),
      ],
    ),
  ],
};

const pip3Definition: DeveloperReferenceDefinition = {
  id: "pip3",
  templateKey: "developer:pip3-reference:v1",
  title: "pip3 Developer Reference",
  description:
    "Python package management fundamentals, reproducible installs, and practical virtual-environment workflows.",
  tags: ["pip3", "pip", "Python", "Developer reference"],
  decks: [
    deck(
      "introduction",
      "01 · pip3 Introduction",
      "The package commands used in most Python projects, invoked through the intended interpreter.",
      [
        card(
          "version",
          "Verify pip and its interpreter",
          "python3 -m pip --version",
          "Shows the pip version and Python installation that will receive packages. This is less ambiguous than a bare pip3 executable.",
          "python3 -m pip --version",
        ),
        card(
          "install",
          "Install a package",
          "python3 -m pip install <package>",
          "Resolves and installs a package plus its dependencies into the active environment.",
          "python3 -m pip install requests",
        ),
        card(
          "pin",
          "Install a specific version",
          "python3 -m pip install '<package>==<version>'",
          "Pins the requested project to one exact version.",
          "python3 -m pip install 'requests==2.32.5'",
        ),
        card(
          "uninstall",
          "Uninstall a package",
          "python3 -m pip uninstall <package>",
          "Removes an installed distribution after confirmation.",
          "python3 -m pip uninstall requests",
        ),
        card(
          "list",
          "List installed packages",
          "python3 -m pip list",
          "Displays installed project names and versions; --outdated compares them with the index.",
          "python3 -m pip list --outdated",
        ),
        card(
          "show",
          "Inspect package metadata",
          "python3 -m pip show <package>",
          "Shows version, location, dependencies, and reverse dependency metadata.",
          "python3 -m pip show requests",
        ),
        card(
          "freeze",
          "Capture installed versions",
          "python3 -m pip freeze",
          "Prints installed packages in requirements format; it is an environment snapshot, not a complete dependency-locking strategy.",
          "python3 -m pip freeze > requirements.snapshot.txt",
        ),
        card(
          "requirements",
          "Install a requirements file",
          "python3 -m pip install -r <file>",
          "Installs all requirement entries and included constraint files.",
          "python3 -m pip install -r requirements.txt",
        ),
        card(
          "upgrade",
          "Upgrade one package",
          "python3 -m pip install --upgrade <package>",
          "Selects the newest compatible release for the requested package under the active constraints.",
          "python3 -m pip install --upgrade requests",
        ),
        card(
          "editable",
          "Install a local project for development",
          "python3 -m pip install --editable <path>",
          "Creates an editable installation so source edits are immediately visible.",
          "python3 -m pip install --editable '.[dev]'",
        ),
        card(
          "index",
          "Inspect available versions",
          "python3 -m pip index versions <package>",
          "Queries the configured package index for published versions.",
          "python3 -m pip index versions django",
        ),
        card(
          "check",
          "Check dependency compatibility",
          "python3 -m pip check",
          "Reports missing dependencies or incompatible installed versions.",
          "python3 -m pip check",
        ),
      ],
    ),
    deck(
      "advanced",
      "02 · pip3 Advanced",
      "Constraints, hashes, wheels, diagnostics, indexes, and externally managed Python environments.",
      [
        card(
          "constraints",
          "Constrain transitive versions",
          "python3 -m pip install -r requirements.txt -c constraints.txt",
          "Applies upper bounds or organization-wide versions without declaring new top-level requirements.",
          "python3 -m pip install -r requirements.txt -c constraints.txt",
        ),
        card(
          "hashes",
          "Require artifact hashes",
          "python3 -m pip install --require-hashes -r requirements.txt",
          "Rejects unlisted artifacts and dependencies unless every requirement is pinned and hashed.",
          "python3 -m pip hash wheels/*.whl\npython3 -m pip install --require-hashes -r requirements.txt",
          "bash",
          "Generate hashes from artifacts obtained through a trusted workflow and review index configuration.",
        ),
        card(
          "wheel",
          "Build wheels",
          "python3 -m pip wheel -r requirements.txt --wheel-dir <dir>",
          "Builds or downloads wheel artifacts without installing them.",
          "python3 -m pip wheel -r requirements.txt --wheel-dir ./wheelhouse",
        ),
        card(
          "offline",
          "Download for later installation",
          "python3 -m pip download -r requirements.txt --dest <dir>",
          "Collects distributions for review, caching, or an offline installation.",
          "python3 -m pip download -r requirements.txt --dest ./vendor",
        ),
        card(
          "inspect",
          "Inspect an environment as JSON",
          "python3 -m pip inspect",
          "Emits a machine-readable report of installed distributions and dependency metadata.",
          "python3 -m pip inspect > environment.json",
        ),
        card(
          "config",
          "Inspect pip configuration",
          "python3 -m pip config list\npython3 -m pip config debug",
          "Shows effective settings and the files or environment sources that contributed them.",
          "python3 -m pip config debug",
        ),
        card(
          "vcs",
          "Install a pinned VCS revision",
          "python3 -m pip install '<name> @ git+https://...@<commit>'",
          "Installs a direct reference; a full immutable commit is more reproducible than a moving branch.",
          "python3 -m pip install 'demo @ git+https://example.test/team/demo.git@0123456789abcdef'",
          "bash",
          "Review the repository and pin a trusted commit. Do not embed repository credentials in the URL.",
        ),
        card(
          "managed",
          "Respect externally managed Python",
          "python3 -m venv .venv",
          "Distribution-managed Python installations can reject global pip changes; use a virtual environment or the OS package manager.",
          "python3 -m venv .venv\n. .venv/bin/activate\npython -m pip install -r requirements.txt",
          "bash",
          "Avoid sudo pip and avoid --break-system-packages unless you intentionally accept damage to the managed environment.",
        ),
      ],
    ),
    deck(
      "samples",
      "03 · pip3 Practical Samples",
      "Ten repeatable Python dependency workflows.",
      [
        card(
          "sample-01",
          "Sample 1: Create an isolated environment",
          "python3 -m venv .venv",
          "Creates a project-local interpreter environment before installing dependencies.",
          "python3 -m venv .venv\n. .venv/bin/activate\npython -m pip install --upgrade pip",
        ),
        card(
          "sample-02",
          "Sample 2: Install a reviewed requirements set",
          "python -m pip install -r requirements.txt",
          "Installs the project's declared versions into the active virtual environment.",
          "python -m pip install -r requirements.txt\npython -m pip check",
        ),
        card(
          "sample-03",
          "Sample 3: Separate development tools",
          "python -m pip install -r requirements-dev.txt",
          "Keeps test and lint dependencies out of a production-only requirement set.",
          "python -m pip install -r requirements.txt\npython -m pip install -r requirements-dev.txt",
        ),
        card(
          "sample-04",
          "Sample 4: Work on a local package",
          "python -m pip install -e '.[test]'",
          "Installs the current project editable with an optional dependency group or extra.",
          "python -m pip install --editable '.[test]'\npytest",
        ),
        card(
          "sample-05",
          "Sample 5: Prepare an offline wheelhouse",
          "pip wheel ...; pip install --no-index ...",
          "Builds artifacts online, then installs only from the reviewed local directory.",
          "python3 -m pip wheel -r requirements.txt -w wheelhouse\npython3 -m pip install --no-index --find-links=wheelhouse -r requirements.txt",
        ),
        card(
          "sample-06",
          "Sample 6: Diagnose dependency conflicts",
          "python -m pip check\npython -m pip inspect",
          "Combines a readable compatibility check with structured environment evidence.",
          "python -m pip check\npython -m pip inspect > pip-inspect.json",
        ),
        card(
          "sample-07",
          "Sample 7: Upgrade one dependency only",
          "python -m pip install --upgrade <package>",
          "Limits an update to one direct package and then checks the resulting environment.",
          "python -m pip install --upgrade requests\npython -m pip check",
        ),
        card(
          "sample-08",
          "Sample 8: Record an environment snapshot",
          "python -m pip freeze --all > <file>",
          "Captures exact installed versions for diagnostics or comparison.",
          "python -m pip freeze --all > diagnostics-requirements.txt",
          "bash",
          "Treat freeze output as a snapshot; use your project's reviewed lock or constraint workflow for releases.",
        ),
        card(
          "sample-09",
          "Sample 9: Compare Python installations",
          "python3.12 -m pip --version\npython3.13 -m pip --version",
          "Shows which pip belongs to each explicitly selected interpreter.",
          "python3.12 -m pip show pip\npython3.13 -m pip show pip",
        ),
        card(
          "sample-10",
          "Sample 10: Download one verified artifact",
          "python -m pip download --only-binary=:all: --no-deps <package>",
          "Downloads a wheel without installing dependencies so it can be scanned or hashed first.",
          "python -m pip download --only-binary=:all: --no-deps 'requests==2.32.5' -d artifacts\npython -m pip hash artifacts/*.whl",
        ),
      ],
    ),
  ],
};

const composerDefinition: DeveloperReferenceDefinition = {
  id: "composer",
  templateKey: "developer:composer-reference:v1",
  title: "Composer Developer Reference",
  description:
    "PHP dependency management fundamentals, reproducible builds, and secure practical Composer workflows.",
  tags: ["Composer", "PHP", "Dependencies", "Developer reference"],
  decks: [
    deck(
      "introduction",
      "01 · Composer Introduction",
      "The commands used during normal PHP application and library development.",
      [
        card(
          "help",
          "Discover Composer commands",
          "composer list\ncomposer <command> --help",
          "Lists commands or explains one command and its options.",
          "composer install --help",
        ),
        card(
          "init",
          "Initialize composer.json",
          "composer init",
          "Interactively creates package metadata and dependency sections.",
          "mkdir demo && cd demo\ncomposer init",
        ),
        card(
          "require",
          "Add a production dependency",
          "composer require <package>[:constraint]",
          "Updates composer.json, resolves dependencies, writes the lock file, and installs packages.",
          "composer require monolog/monolog:^3.0",
        ),
        card(
          "install",
          "Install locked dependencies",
          "composer install",
          "Uses composer.lock when present, producing the same selected versions across environments.",
          "composer install --no-interaction",
        ),
        card(
          "update",
          "Update a selected dependency",
          "composer update <package>",
          "Re-resolves only the requested package and permitted dependencies, then updates composer.lock.",
          "composer update monolog/monolog --with-all-dependencies",
        ),
        card(
          "remove",
          "Remove a dependency",
          "composer remove <package>",
          "Removes the requirement, resolves the new graph, and updates installed packages.",
          "composer remove monolog/monolog",
        ),
        card(
          "show",
          "Inspect packages",
          "composer show [package]",
          "Lists installed packages or displays versions, requirements, and metadata for one package.",
          "composer show symfony/console --all",
        ),
        card(
          "outdated",
          "Find available updates",
          "composer outdated",
          "Compares installed or locked versions with newer releases without changing them.",
          "composer outdated --direct",
        ),
        card(
          "validate",
          "Validate project metadata",
          "composer validate",
          "Checks composer.json and the lock file for schema and publication problems.",
          "composer validate --strict",
        ),
        card(
          "autoload",
          "Regenerate the autoloader",
          "composer dump-autoload",
          "Rebuilds vendor/autoload.php after autoload configuration changes.",
          "composer dump-autoload --optimize",
        ),
        card(
          "scripts",
          "Run project scripts",
          "composer run-script <name>",
          "Runs a script declared under the composer.json scripts key.",
          "composer run-script test",
        ),
        card(
          "audit",
          "Audit known vulnerabilities",
          "composer audit",
          "Checks locked or installed packages against configured security advisories.",
          "composer audit --locked",
        ),
      ],
    ),
    deck(
      "advanced",
      "02 · Composer Advanced",
      "Lock semantics, platform constraints, optimized autoloading, repositories, and safer automation.",
      [
        card(
          "lock",
          "Understand install versus update",
          "composer install\ncomposer update",
          "Install honors composer.lock; update resolves allowed versions and rewrites it. Commit the lock file for applications.",
          "composer update vendor/package\ngit diff -- composer.json composer.lock",
        ),
        card(
          "dev",
          "Control development dependencies",
          "composer require --dev <package>\ncomposer install --no-dev",
          "Keeps development tools separate and omits them in production builds.",
          "composer require --dev phpunit/phpunit\ncomposer install --no-dev",
        ),
        card(
          "platform",
          "Model and verify the PHP platform",
          "composer config platform.php <version>\ncomposer check-platform-reqs",
          "Resolves against a declared PHP version, then verifies the real deployment runtime separately.",
          "composer config platform.php 8.3.0\ncomposer check-platform-reqs --no-dev",
        ),
        card(
          "autoload-optimize",
          "Optimize production autoloading",
          "composer dump-autoload --optimize --classmap-authoritative",
          "Builds an optimized class map and disables fallback class discovery.",
          "composer install --no-dev --optimize-autoloader --classmap-authoritative",
        ),
        card(
          "repositories",
          "Configure repositories deliberately",
          "composer repo list|add|remove",
          "Manages non-Packagist repositories and their priority in composer.json.",
          "composer repo add internal composer https://packages.example.test",
          "bash",
          "Use authenticated HTTPS and protected credential storage; repository code and Composer plugins execute with developer privileges.",
        ),
        card(
          "why",
          "Explain dependency decisions",
          "composer why <package>\ncomposer why-not <package> <version>",
          "Shows which package requires another or which constraint blocks an upgrade.",
          "composer why psr/log\ncomposer why-not php 8.4",
        ),
        card(
          "dry-run",
          "Preview dependency changes",
          "composer update --dry-run",
          "Runs the solver and prints planned operations without changing files.",
          "composer update symfony/console --with-all-dependencies --dry-run",
        ),
        card(
          "automation-safety",
          "Limit automation side effects",
          "composer install --no-interaction --no-scripts --no-plugins",
          "Can disable prompts, project scripts, and plugins during inspection or restricted build stages.",
          "composer install --no-interaction --no-scripts --no-plugins",
          "bash",
          "Enable required scripts or plugins only after reviewing their source and purpose.",
        ),
      ],
    ),
    deck(
      "samples",
      "03 · Composer Practical Samples",
      "Ten application, library, CI, update, and troubleshooting workflows.",
      [
        card(
          "sample-01",
          "Sample 1: Start a PHP application",
          "composer init; composer require ...",
          "Creates metadata and adds the first runtime package.",
          "composer init --name=acme/demo --type=project\ncomposer require symfony/console",
        ),
        card(
          "sample-02",
          "Sample 2: Reproduce a checked-in build",
          "composer install --no-interaction",
          "Installs the exact lock-file graph and fails instead of prompting in CI.",
          "composer validate --strict\ncomposer install --no-interaction --prefer-dist",
        ),
        card(
          "sample-03",
          "Sample 3: Build production dependencies",
          "composer install --no-dev --optimize-autoloader",
          "Omits development tools and optimizes class lookup for deployment.",
          "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader\ncomposer check-platform-reqs --no-dev",
        ),
        card(
          "sample-04",
          "Sample 4: Add a test runner",
          "composer require --dev <package>",
          "Records a tool as development-only and leaves runtime requirements clean.",
          "composer require --dev phpunit/phpunit\ncomposer exec phpunit",
        ),
        card(
          "sample-05",
          "Sample 5: Update one package safely",
          "composer update <package> --with-all-dependencies",
          "Previews, performs, then validates a targeted update.",
          "composer update monolog/monolog --with-all-dependencies --dry-run\ncomposer update monolog/monolog --with-all-dependencies\ncomposer audit",
        ),
        card(
          "sample-06",
          "Sample 6: Diagnose a blocked PHP upgrade",
          "composer why-not php <version>",
          "Reports the exact constraints preventing the target runtime version.",
          "composer why-not php 8.4\ncomposer show --platform",
        ),
        card(
          "sample-07",
          "Sample 7: Validate autoload mappings",
          "composer dump-autoload --strict-psr",
          "Regenerates autoload data and fails on PSR mapping errors.",
          "composer dump-autoload --optimize --strict-psr",
        ),
        card(
          "sample-08",
          "Sample 8: Run project quality scripts",
          "composer run-script <name>",
          "Uses project-defined commands so local and CI workflows match.",
          "composer run-script lint\ncomposer run-script test",
        ),
        card(
          "sample-09",
          "Sample 9: Review direct outdated packages",
          "composer outdated --direct",
          "Limits the report to packages explicitly required by the project.",
          "composer outdated --direct --strict",
        ),
        card(
          "sample-10",
          "Sample 10: Inspect an untrusted project first",
          "composer install --no-scripts --no-plugins",
          "Installs without executing package plugins or project lifecycle scripts during an initial review.",
          "composer validate --strict\ncomposer audit --locked\ncomposer install --no-scripts --no-plugins",
          "bash",
          "Dependency source itself still becomes local code; inspect provenance and advisories before executing the application.",
        ),
      ],
    ),
  ],
};

const xpathDefinition: DeveloperReferenceDefinition = {
  id: "xpath",
  templateKey: "developer:xpath-reference:v1",
  title: "XPath Developer Reference",
  description:
    "Portable XML and HTML path fundamentals, advanced axes and namespaces, and robust locator examples.",
  tags: ["XPath", "XML", "HTML", "Developer reference"],
  decks: [
    deck(
      "introduction",
      "01 · XPath Introduction",
      "The XPath 1.0-compatible core supported by browsers and most automation tools.",
      [
        card(
          "root",
          "Select from the document root",
          "/catalog/book",
          "An absolute path starts at the document node and selects matching direct children at each step.",
          "<catalog><book/><book/></catalog>\nXPath: /catalog/book",
          "xml",
        ),
        card(
          "descendant",
          "Select descendants",
          "//book",
          "A double slash searches matching descendant elements below the current context.",
          "XPath: //section//a",
        ),
        card(
          "attribute",
          "Select attributes",
          "//book/@id",
          "The @ axis selects attributes instead of element nodes.",
          "XPath: //input/@name",
        ),
        card(
          "predicate",
          "Filter with a predicate",
          "//book[@category='web']",
          "Square brackets keep nodes that satisfy the condition in the current context.",
          "XPath: //input[@type='email']",
        ),
        card(
          "position",
          "Select by position",
          "//book[1]\n//book[last()]",
          "A numeric predicate selects by XPath position, which starts at one.",
          "XPath: /catalog/book[1]",
        ),
        card(
          "text",
          "Select or test text nodes",
          "//title/text()\n//title[text()='Guide']",
          "text() addresses direct text-node children; equality uses their string value.",
          "XPath: //button[normalize-space(.)='Save']",
        ),
        card(
          "contains",
          "Match part of a string",
          "contains(<value>, <substring>)",
          "Returns true when the first string contains the second.",
          "XPath: //div[contains(@class, 'notice')]",
        ),
        card(
          "starts-with",
          "Match a string prefix",
          "starts-with(<value>, <prefix>)",
          "Returns true when a string begins with the required prefix.",
          "XPath: //a[starts-with(@href, '/docs/')]",
        ),
        card(
          "logic",
          "Combine conditions",
          "condition and condition\ncondition or condition",
          "Combines Boolean predicate expressions with explicit precedence when parentheses are used.",
          "XPath: //input[@required and (@type='email' or @type='text')]",
        ),
        card(
          "wildcard",
          "Match unknown names",
          "//*\n//@*",
          "An asterisk matches any element or attribute on the chosen axis.",
          "XPath: /catalog/*[@id]",
        ),
        card(
          "relative",
          "Evaluate relative to context",
          ".//item\n./@id",
          "A leading dot starts from the node supplied by the host application instead of the document root.",
          "Context: <section>\nXPath: .//button[@type='submit']",
          "xml",
        ),
        card(
          "parent",
          "Move to the parent",
          "//price/..\n//price/parent::book",
          "Two dots or the parent axis selects the containing element.",
          "XPath: //span[@class='error']/..",
        ),
      ],
    ),
    deck(
      "advanced",
      "02 · XPath Advanced",
      "Namespaces, axes, unions, version boundaries, safe literals, and query performance.",
      [
        card(
          "namespaces",
          "Bind namespace prefixes in the host",
          "//lib:book",
          "XPath prefixes are resolved by the host application's namespace context; a document's default namespace does not automatically bind an XPath prefix.",
          "XML namespace: urn:library\nBinding: lib -> urn:library\nXPath: //lib:book",
          "xml",
        ),
        card(
          "axes",
          "Navigate explicit axes",
          "ancestor::\ndescendant::\nfollowing-sibling::\npreceding-sibling::",
          "Axes express direction and relationship when a simple child path is insufficient.",
          "XPath: //label[normalize-space(.)='Email']/following-sibling::input[1]",
        ),
        card(
          "union",
          "Combine node selections",
          "//title | //heading",
          "The union operator combines node sequences and removes duplicate nodes in document order.",
          "XPath: //h1 | //h2 | //h3",
        ),
        card(
          "siblings",
          "Select a related sibling",
          "following-sibling::<name>[1]",
          "Starts at a stable node and selects the nearest matching later sibling.",
          "XPath: //dt[.='Status']/following-sibling::dd[1]",
        ),
        card(
          "normalize",
          "Normalize whitespace",
          "normalize-space(<value>)",
          "Trims leading and trailing XML whitespace and collapses internal runs to one space.",
          "XPath: //button[normalize-space(.)='Create account']",
        ),
        card(
          "versions",
          "Know the XPath version boundary",
          "XPath 1.0 vs 2.0/3.1",
          "Browsers commonly expose XPath 1.0, while XPath 2.0 and 3.1 add sequences, richer types, regular expressions, maps, arrays, and more functions.",
          "XPath 1.0 portable: //item[number(@price) > 10]\nXPath 2.0+: //item[matches(@sku, '^A-')]",
        ),
        card(
          "literals",
          "Encode dynamic string literals safely",
          "Host API + bound variables or a literal builder",
          "XPath has no universal parameter syntax. Host APIs should bind variables when supported or correctly compose literals containing both quote types.",
          "Do not concatenate raw user input into: //user[@name='...']",
          "bash",
          "Treat untrusted XPath fragments as code. Allow-list query structure and pass data through supported host bindings.",
        ),
        card(
          "performance",
          "Prefer scoped paths",
          "/catalog/book[...] instead of //*[...]",
          "Starting from a known context and using named steps reduces needless descendant scans and improves clarity.",
          "Context: catalog element\nXPath: ./book[@available='yes']/title",
        ),
      ],
    ),
    deck(
      "samples",
      "03 · XPath Practical Samples",
      "Ten robust XML, HTML, testing, and automation locators.",
      [
        card(
          "sample-01",
          "Sample 1: Select affordable books",
          "/catalog/book[price <= 30]/title",
          "Filters book elements by their numeric child value and selects their titles.",
          "XPath: /catalog/book[number(price) <= 30]/title",
        ),
        card(
          "sample-02",
          "Sample 2: Select an accessible form field",
          "//label[...]/following::input[1]",
          "Anchors on visible label text, then selects the nearest later input.",
          "XPath: //label[normalize-space(.)='Email']/following::input[1]",
        ),
        card(
          "sample-03",
          "Sample 3: Match one CSS class token",
          "contains(concat(' ', normalize-space(@class), ' '), ' token ')",
          "Adds spaces around the normalized class list to avoid partial-name matches.",
          "XPath: //div[contains(concat(' ', normalize-space(@class), ' '), ' alert ')]",
        ),
        card(
          "sample-04",
          "Sample 4: Select external links",
          "//a[starts-with(@href, 'https://')]",
          "Finds anchor elements whose href uses HTTPS.",
          "XPath: //main//a[starts-with(@href, 'https://')]",
        ),
        card(
          "sample-05",
          "Sample 5: Read an XML attribute",
          "//server[@role='primary']/@host",
          "Selects the host attribute of servers with the required role.",
          "XPath: /config/servers/server[@role='primary']/@host",
        ),
        card(
          "sample-06",
          "Sample 6: Select the last table row",
          "//table[@id='jobs']/tbody/tr[last()]",
          "Uses one-based context position to select the final matching row.",
          "XPath: //table[@id='jobs']/tbody/tr[last()]",
        ),
        card(
          "sample-07",
          "Sample 7: Locate a button by normalized text",
          "//button[normalize-space(.)='Save']",
          "Handles harmless leading, trailing, and repeated whitespace without using a fragile absolute path.",
          "XPath: //form[@id='profile']//button[normalize-space(.)='Save']",
        ),
        card(
          "sample-08",
          "Sample 8: Select a following status value",
          "//dt[.='Build']/following-sibling::dd[1]",
          "Anchors a definition-list value to its stable label.",
          "XPath: //dt[normalize-space(.)='Build']/following-sibling::dd[1]",
        ),
        card(
          "sample-09",
          "Sample 9: Query namespaced XML",
          "//atom:entry/atom:title",
          "Uses a host-bound prefix to select elements in the Atom namespace.",
          "Binding: atom -> http://www.w3.org/2005/Atom\nXPath: //atom:entry/atom:title",
          "xml",
        ),
        card(
          "sample-10",
          "Sample 10: Scope a test locator",
          ".//*[@data-testid='result']",
          "Evaluates below a component element and avoids matching identical identifiers elsewhere on the page.",
          "Context: dialog element\nXPath: .//*[@data-testid='result']",
        ),
      ],
    ),
  ],
};

const jsonPathDefinition: DeveloperReferenceDefinition = {
  id: "jsonpath",
  templateKey: "developer:jsonpath-reference:v1",
  title: "JSONPath Developer Reference",
  description:
    "RFC 9535 JSONPath fundamentals, portability rules, and practical selectors for nested JSON data.",
  tags: ["JSONPath", "JSON", "RFC 9535", "Developer reference"],
  decks: [
    deck(
      "introduction",
      "01 · JSONPath Introduction",
      "The standardized RFC 9535 selectors used to produce a nodelist from JSON.",
      [
        card(
          "root",
          "Start at the root",
          "$",
          "Every query outside a filter expression begins with the root identifier and initially selects the whole JSON value.",
          "JSONPath: $",
        ),
        card(
          "name",
          "Select an object member",
          "$.store",
          "A name selector chooses a named member from each input object.",
          "JSONPath: $.store.book",
        ),
        card(
          "bracket-name",
          "Select a quoted member name",
          "$['member name']",
          "Bracket notation handles spaces, punctuation, escapes, and names that are awkward after a dot.",
          "JSONPath: $['store']['book']",
        ),
        card(
          "index",
          "Select an array item",
          "$.items[0]",
          "An index selector chooses one array element; zero is the first item.",
          "JSONPath: $.store.book[0].title",
        ),
        card(
          "negative-index",
          "Count backward from the end",
          "$.items[-1]",
          "A negative index is relative to the array length, so -1 selects the last item.",
          "JSONPath: $.events[-1]",
        ),
        card(
          "wildcard",
          "Select all children",
          "$.items[*]\n$.*",
          "A wildcard selects every array element or object member at that step.",
          "JSONPath: $.store.book[*].author",
        ),
        card(
          "slice",
          "Select an array slice",
          "$.items[start:end:step]",
          "Slice syntax selects a range using zero-based bounds; the end bound is excluded.",
          "JSONPath: $.items[0:10:2]",
        ),
        card(
          "descendant",
          "Search descendants",
          "$..price",
          "A descendant segment applies the following selector throughout the nested value.",
          "JSONPath: $..price",
        ),
        card(
          "filter",
          "Filter array members",
          "$.items[?@.price < 10]",
          "A filter selector keeps nodes for which its logical expression is true.",
          "JSONPath: $.store.book[?@.price < 10].title",
        ),
        card(
          "logical",
          "Combine filter tests",
          "?(@.active && @.score >= 80)",
          "Logical AND, OR, and NOT combine comparisons and existence tests in filters.",
          "JSONPath: $.users[?(@.active && @.score >= 80)].name",
        ),
        card(
          "existence",
          "Test whether a path selects nodes",
          "?@.isbn",
          "A standalone relative query in a filter is true when it selects at least one node, even if a selected value is false or null.",
          "JSONPath: $.books[?@.isbn]",
        ),
        card(
          "functions",
          "Use standardized filter functions",
          "length()  count()  match()  search()  value()",
          "RFC 9535 defines typed functions for filters; an implementation can add extensions under separate names.",
          "JSONPath: $.users[?length(@.roles) >= 2].name",
        ),
      ],
    ),
    deck(
      "advanced",
      "02 · JSONPath Advanced",
      "Nodelists, normalized paths, filter scope, typing, escaping, portability, and performance.",
      [
        card(
          "nodelist",
          "Expect a nodelist result",
          "$..id",
          "A JSONPath query selects zero or more nodes. Host libraries decide how that nodelist is represented in their API.",
          "JSONPath: $..id\nPossible result values: [1, 7, 12]",
        ),
        card(
          "singular",
          "Recognize singular queries",
          "$.user.name\n$.items[0]",
          "A syntactically singular query uses only name and index selectors; it can identify at most one node and is valid in value comparisons.",
          "JSONPath: $.settings.theme",
        ),
        card(
          "normalized-path",
          "Use normalized paths as identifiers",
          "$['store']['book'][0]['title']",
          "A normalized path is an unambiguous bracket-form identifier for one selected node.",
          "Normalized path: $['users'][3]['email']",
        ),
        card(
          "filter-scope",
          "Use @ for the current filter node",
          "$.items[?@.enabled]",
          "Inside a filter, @ refers to the candidate node while $ still refers to the query root.",
          "JSONPath: $.orders[?@.total > $.limits.minimum]",
        ),
        card(
          "types",
          "Compare compatible values",
          "?@.price == 10",
          "JSON numbers, strings, Booleans, null, and query results have defined comparison behavior; quoted '10' is not the number 10.",
          "JSONPath: $.items[?(@.status == 'ready' && @.attempts < 3)]",
        ),
        card(
          "escaping",
          "Escape member names and strings",
          "$['a\\'b']",
          "Quoted selectors use JSON-style escapes, with an escaped matching quote when necessary.",
          "JSONPath: $['line\\nbreak']",
        ),
        card(
          "portability",
          "Separate RFC syntax from legacy dialects",
          "RFC 9535 query",
          "Older libraries can differ on rootless paths, script expressions, regular expressions, result ordering, or filter punctuation.",
          "Portable first choice: $.items[?@.active]\nVerify against the selected library's RFC 9535 support.",
        ),
        card(
          "performance",
          "Scope descendant searches",
          "$.catalog.books[*] instead of $..*",
          "Named child segments reduce traversal work and better communicate the expected JSON shape.",
          "JSONPath: $.catalog.books[?@.available].title",
        ),
      ],
    ),
    deck(
      "samples",
      "03 · JSONPath Practical Samples",
      "Ten RFC-oriented selectors for APIs, catalogs, monitoring, and nested configuration.",
      [
        card(
          "sample-01",
          "Sample 1: Select every book title",
          "$.store.book[*].title",
          "Traverses a named array and selects the title member of every item.",
          "JSONPath: $.store.book[*].title",
        ),
        card(
          "sample-02",
          "Sample 2: Select inexpensive books",
          "$.store.book[?@.price <= 20].title",
          "Filters array entries numerically and returns only their titles.",
          "JSONPath: $.store.book[?@.price <= 20].title",
        ),
        card(
          "sample-03",
          "Sample 3: Read the latest event",
          "$.events[-1]",
          "Uses the standardized negative index to select the final array entry.",
          "JSONPath: $.events[-1]",
        ),
        card(
          "sample-04",
          "Sample 4: Find IDs at any depth",
          "$..id",
          "Searches descendants and selects every member named id.",
          "JSONPath: $..id",
        ),
        card(
          "sample-05",
          "Sample 5: Select active administrators",
          "$.users[?(@.active && @.role == 'admin')].email",
          "Combines a Boolean member and a string comparison in one filter.",
          "JSONPath: $.users[?(@.active && @.role == 'admin')].email",
        ),
        card(
          "sample-06",
          "Sample 6: Select records with an error",
          "$.results[?@.error]",
          "Uses existence rather than truthiness, so a present error member is selected even when its value is null.",
          "JSONPath: $.results[?@.error]",
        ),
        card(
          "sample-07",
          "Sample 7: Select the first page",
          "$.items[0:25]",
          "Returns at most the first 25 array entries because the end bound is exclusive.",
          "JSONPath: $.items[0:25]",
        ),
        card(
          "sample-08",
          "Sample 8: Match a standardized name pattern",
          "$.users[?match(@.name, '^[A-Z][a-z]+$')]",
          "Uses the RFC match function, which requires the entire string to match the I-Regexp pattern.",
          "JSONPath: $.users[?match(@.name, '^[A-Z][a-z]+$')].name",
        ),
        card(
          "sample-09",
          "Sample 9: Select non-empty tag lists",
          "$.items[?length(@.tags) > 0]",
          "Keeps items whose tags value has a positive standardized length.",
          "JSONPath: $.items[?length(@.tags) > 0].name",
        ),
        card(
          "sample-10",
          "Sample 10: Address a punctuation-heavy member",
          "$['build.status']['last-run']",
          "Uses quoted name selectors so dots and hyphens remain part of member names.",
          "JSONPath: $['build.status']['last-run']",
        ),
      ],
    ),
  ],
};

export const additionalDeveloperReferenceDefinitions: DeveloperReferenceDefinition[] =
  [
    cmdDefinition,
    powershellDefinition,
    bashZshDefinition,
    pip3Definition,
    composerDefinition,
    xpathDefinition,
    jsonPathDefinition,
  ];
