// Generated by scripts/generate-third-party-notices.mjs. Do not edit.
export const thirdPartyNoticeGraphSha256 =
  "df0c285a27a595b7a55a38854f3cb0c4d17a4843b16567e642f66df7dc1ddc13";
export const thirdPartyNoticeComponentCount = 146;
export const thirdPartyNoticePages = [
  {
    key: "third-party-overview",
    title: "Third-Party Notices",
    source:
      "# Third-Party Licenses\n\nFlash-n-Flip ships 146 third-party components covered by 78 distinct license or notice documents.\n\n[Open complete offline notices](/legal/documents/third-party-notices.html)\n\nThe complete document is installed with the application and remains available without an internet connection. External project and canonical license links are supplementary only.\n",
  },
] as const;
