// Generated by scripts/generate-third-party-notices.mjs. Do not edit.
export const thirdPartyNoticeGraphSha256 =
  "67301e4e9b48e6550e285f2b0d096578f9c76267e0e6535ed4506ec8d17cc356";
export const thirdPartyNoticeComponentCount = 146;
export const thirdPartyNoticePages = [
  {
    key: "third-party-overview",
    title: "Third-Party Notices",
    source:
      "# Third-Party Licenses\n\nFlash-n-Flip ships 146 third-party components covered by 78 distinct license or notice documents.\n\n[Open complete offline notices](/legal/documents/third-party-notices.html)\n\nThe complete document is installed with the application and remains available without an internet connection. External project and canonical license links are supplementary only.\n",
  },
] as const;
