/* Generated by scripts/generate-brand-assets.mjs. Do not edit directly. */
export const brandBaseColors = {
  yellow: "#F5C505",
  navy: "#0C276C",
  blue: "#0F6AFA",
} as const;

export const brandNeutralColors = {
  gray50: "#F7F6F2",
  gray200: "#D8D9DD",
  gray500: "#666B75",
  gray800: "#242832",
} as const;

export const brandThemes = {
  bright: {
    ink: "#0C276C",
    muted: "#666B75",
    paper: "#F7F3E4",
    surface: "#F7F6F2",
    surfaceRaised: "#FFFFFF",
    primary: "#0F6AFA",
    primaryStrong: "#0E4CBA",
    primarySoft: "#E0E8F3",
    border: "#D8D9DD",
    highlight: "#F5C505",
  },
  dark: {
    ink: "#F7F6F2",
    muted: "#D8D9DD",
    paper: "#1B1E26",
    surface: "#242832",
    surfaceRaised: "#3E424B",
    primary: "#0F6AFA",
    primaryStrong: "#0E55CD",
    primarySoft: "#203456",
    border: "#424650",
    highlight: "#F5C505",
  },
} as const;
