/* Generated by scripts/generate-brand-assets.mjs. Do not edit directly. */
export const brandBaseColors = {
  yellow: "#F5C505",
  navy: "#0C276C",
  blue: "#0F6AFA",
} as const;

export const brandThemes = {
  bright: {
    ink: "#0C276C",
    muted: "#5F709E",
    paper: "#FEFCF0",
    surface: "#FFFEFA",
    surfaceRaised: "#FFFFFF",
    primary: "#0F6AFA",
    primaryStrong: "#0E4CBA",
    primarySoft: "#E2EDFE",
    border: "#D8DCE7",
    highlight: "#F5C505",
  },
  dark: {
    ink: "#FEFAEB",
    muted: "#B1BAD0",
    paper: "#07173F",
    surface: "#091C4E",
    surfaceRaised: "#0A215B",
    primary: "#0F6AFA",
    primaryStrong: "#0E55CD",
    primarySoft: "#0D3488",
    border: "#0D3A94",
    highlight: "#F5C505",
  },
} as const;
